In [1]:
import os
os.environ['SPARK_HOME'] = 'C:/Users/RubyEllik/spark-3.5.2-bin-hadoop3'
os.environ['PATH'] += os.pathsep + os.path.join(os.environ['SPARK_HOME'], 'bin')

In [2]:
import os
from pyspark.sql import SparkSession

# Configure Spark
os.environ['SPARK_HOME'] = 'C:/Users/RubyEllik/spark-3.5.2-bin-hadoop3'
os.environ['PATH'] += os.pathsep + os.path.join(os.environ['SPARK_HOME'], 'bin')

# Create Spark session
spark = SparkSession.builder \
    .appName("Jupyter Notebook") \
    .getOrCreate()

In [3]:
spark

#### Read data and make the column names as the header

In [4]:
df=spark.read.csv('housing.csv', header=True, inferSchema=True)

In [5]:
df

DataFrame[longitude: double, latitude: double, housing_median_age: double, total_rooms: double, total_bedrooms: double, population: double, households: double, median_income: double, median_house_value: double, ocean_proximity: string]

In [6]:
df.show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1627.0|         280.0|     565.0|     259.0|       3.8462|          342200.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|      919.0|         213.0|     413.0|     193.0|       4.0368|          269700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     2535.0|         489.0|    1094.0|     514.0|       3.6591|          299200.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3104.0|         687.0|    1157.0|     647.0|         3.12|          241400.0|       NEAR BAY|
|  -122.26|   37.84|              42.0|     2555.0|         665.0|    1206.0|     595.0|       2.0804|          226700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3549.0|         707.0|    1551.0|     714.0|       3.6912|          261100.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2202.0|         434.0|     910.0|     402.0|       3.2031|          281500.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     3503.0|         752.0|    1504.0|     734.0|       3.2705|          241800.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2491.0|         474.0|    1098.0|     468.0|        3.075|          213500.0|       NEAR BAY|
|  -122.26|   37.84|              52.0|      696.0|         191.0|     345.0|     174.0|       2.6736|          191300.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2643.0|         626.0|    1212.0|     620.0|       1.9167|          159200.0|       NEAR BAY|
|  -122.26|   37.85|              50.0|     1120.0|         283.0|     697.0|     264.0|        2.125|          140000.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1966.0|         347.0|     793.0|     331.0|        2.775|          152500.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1228.0|         293.0|     648.0|     303.0|       2.1202|          155500.0|       NEAR BAY|
|  -122.26|   37.84|              50.0|     2239.0|         455.0|     990.0|     419.0|       1.9911|          158700.0|       NEAR BAY|
|  -122.27|   37.84|              52.0|     1503.0|         298.0|     690.0|     275.0|       2.6033|          162900.0|       NEAR BAY|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

#### Get the number of rows and columns

In [7]:
df.count(),len(df.columns)

(20640, 10)

#### First 10 records, where data is not truncated

In [8]:
df.show(10, truncate=False)

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|-122.23  |37.88   |41.0              |880.0      |129.0         |322.0     |126.0     |8.3252       |452600.0          |NEAR BAY       |
|-122.22  |37.86   |21.0              |7099.0     |1106.0        |2401.0    |1138.0    |8.3014       |358500.0          |NEAR BAY       |
|-122.24  |37.85   |52.0              |1467.0     |190.0         |496.0     |177.0     |7.2574       |352100.0          |NEAR BAY       |
|-122.25  |37.85   |52.0              |1274.0     |235.0         |558.0     |219.0     |5.6431       |341300.0          |NEAR BAY       |
|-122.25  |37.85   |52.0              |1627.0     |280.0         |565.0     |259.0     |3.8462       |342200.0          |NEAR BAY       |
|-122.25  |37.85   |52.0              |919.0      |213.0         |413.0     |193.0     |4.0368       |269700.0          |NEAR BAY       |
|-122.25  |37.84   |52.0              |2535.0     |489.0         |1094.0    |514.0     |3.6591       |299200.0          |NEAR BAY       |
|-122.25  |37.84   |52.0              |3104.0     |687.0         |1157.0    |647.0     |3.12         |241400.0          |NEAR BAY       |
|-122.26  |37.84   |42.0              |2555.0     |665.0         |1206.0    |595.0     |2.0804       |226700.0          |NEAR BAY       |
|-122.25  |37.84   |52.0              |3549.0     |707.0         |1551.0    |714.0     |3.6912       |261100.0          |NEAR BAY       |
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 10 rows

In [9]:
df.select('housing_median_age').show()

+------------------+
|housing_median_age|
+------------------+
|              41.0|
|              21.0|
|              52.0|
|              52.0|
|              52.0|
|              52.0|
|              52.0|
|              52.0|
|              42.0|
|              52.0|
|              52.0|
|              52.0|
|              52.0|
|              52.0|
|              52.0|
|              50.0|
|              52.0|
|              52.0|
|              50.0|
|              52.0|
+------------------+
only showing top 20 rows

#### Select All coulmns

In [10]:
df.select([col for col in df.columns]).show()
#df.select("*").show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1627.0|         280.0|     565.0|     259.0|       3.8462|          342200.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|      919.0|         213.0|     413.0|     193.0|       4.0368|          269700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     2535.0|         489.0|    1094.0|     514.0|       3.6591|          299200.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3104.0|         687.0|    1157.0|     647.0|         3.12|          241400.0|       NEAR BAY|
|  -122.26|   37.84|              42.0|     2555.0|         665.0|    1206.0|     595.0|       2.0804|          226700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3549.0|         707.0|    1551.0|     714.0|       3.6912|          261100.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2202.0|         434.0|     910.0|     402.0|       3.2031|          281500.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     3503.0|         752.0|    1504.0|     734.0|       3.2705|          241800.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2491.0|         474.0|    1098.0|     468.0|        3.075|          213500.0|       NEAR BAY|
|  -122.26|   37.84|              52.0|      696.0|         191.0|     345.0|     174.0|       2.6736|          191300.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2643.0|         626.0|    1212.0|     620.0|       1.9167|          159200.0|       NEAR BAY|
|  -122.26|   37.85|              50.0|     1120.0|         283.0|     697.0|     264.0|        2.125|          140000.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1966.0|         347.0|     793.0|     331.0|        2.775|          152500.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1228.0|         293.0|     648.0|     303.0|       2.1202|          155500.0|       NEAR BAY|
|  -122.26|   37.84|              50.0|     2239.0|         455.0|     990.0|     419.0|       1.9911|          158700.0|       NEAR BAY|
|  -122.27|   37.84|              52.0|     1503.0|         298.0|     690.0|     275.0|       2.6033|          162900.0|       NEAR BAY|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

#### To select column by index

In [11]:
df.select(df.columns[:3]).show(3)

+---------+--------+------------------+
|longitude|latitude|housing_median_age|
+---------+--------+------------------+
|  -122.23|   37.88|              41.0|
|  -122.22|   37.86|              21.0|
|  -122.24|   37.85|              52.0|
+---------+--------+------------------+
only showing top 3 rows

In [12]:
df.select(df.columns[2:4]).show(3)

+------------------+-----------+
|housing_median_age|total_rooms|
+------------------+-----------+
|              41.0|      880.0|
|              21.0|     7099.0|
|              52.0|     1467.0|
+------------------+-----------+
only showing top 3 rows

In [13]:
#df.collect()[0]   #0th Row and all columns in 0th row
df.collect()[0][0] # displays 1st element

-122.23

##### select() is a transformation that returns a new DataFrame and holds the columns that are selected whereas collect() is an action that returns the entire data set in an Array to the driver.

In [14]:
######################################################################################################################

#### WithColumn

In [15]:
from pyspark.sql.functions import col
df.withColumn("total_rooms",col("total_rooms")*1).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1627.0|         280.0|     565.0|     259.0|       3.8462|          342200.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|      919.0|         213.0|     413.0|     193.0|       4.0368|          269700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     2535.0|         489.0|    1094.0|     514.0|       3.6591|          299200.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3104.0|         687.0|    1157.0|     647.0|         3.12|          241400.0|       NEAR BAY|
|  -122.26|   37.84|              42.0|     2555.0|         665.0|    1206.0|     595.0|       2.0804|          226700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3549.0|         707.0|    1551.0|     714.0|       3.6912|          261100.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2202.0|         434.0|     910.0|     402.0|       3.2031|          281500.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     3503.0|         752.0|    1504.0|     734.0|       3.2705|          241800.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2491.0|         474.0|    1098.0|     468.0|        3.075|          213500.0|       NEAR BAY|
|  -122.26|   37.84|              52.0|      696.0|         191.0|     345.0|     174.0|       2.6736|          191300.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2643.0|         626.0|    1212.0|     620.0|       1.9167|          159200.0|       NEAR BAY|
|  -122.26|   37.85|              50.0|     1120.0|         283.0|     697.0|     264.0|        2.125|          140000.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1966.0|         347.0|     793.0|     331.0|        2.775|          152500.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1228.0|         293.0|     648.0|     303.0|       2.1202|          155500.0|       NEAR BAY|
|  -122.26|   37.84|              50.0|     2239.0|         455.0|     990.0|     419.0|       1.9911|          158700.0|       NEAR BAY|
|  -122.27|   37.84|              52.0|     1503.0|         298.0|     690.0|     275.0|       2.6033|          162900.0|       NEAR BAY|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

#### Rename A Column

In [16]:
df.withColumnRenamed("total_rooms","Total_rooms").show(truncate=False)

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|Total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|-122.23  |37.88   |41.0              |880.0      |129.0         |322.0     |126.0     |8.3252       |452600.0          |NEAR BAY       |
|-122.22  |37.86   |21.0              |7099.0     |1106.0        |2401.0    |1138.0    |8.3014       |358500.0          |NEAR BAY       |
|-122.24  |37.85   |52.0              |1467.0     |190.0         |496.0     |177.0     |7.2574       |352100.0          |NEAR BAY       |
|-122.25  |37.85   |52.0              |1274.0     |235.0         |558.0     |219.0     |5.6431       |341300.0          |NEAR BAY       |
|-122.25  |37.85   |52.0              |1627.0     |280.0         |565.0     |259.0     |3.8462       |342200.0          |NEAR BAY       |
|-122.25  |37.85   |52.0              |919.0      |213.0         |413.0     |193.0     |4.0368       |269700.0          |NEAR BAY       |
|-122.25  |37.84   |52.0              |2535.0     |489.0         |1094.0    |514.0     |3.6591       |299200.0          |NEAR BAY       |
|-122.25  |37.84   |52.0              |3104.0     |687.0         |1157.0    |647.0     |3.12         |241400.0          |NEAR BAY       |
|-122.26  |37.84   |42.0              |2555.0     |665.0         |1206.0    |595.0     |2.0804       |226700.0          |NEAR BAY       |
|-122.25  |37.84   |52.0              |3549.0     |707.0         |1551.0    |714.0     |3.6912       |261100.0          |NEAR BAY       |
|-122.26  |37.85   |52.0              |2202.0     |434.0         |910.0     |402.0     |3.2031       |281500.0          |NEAR BAY       |
|-122.26  |37.85   |52.0              |3503.0     |752.0         |1504.0    |734.0     |3.2705       |241800.0          |NEAR BAY       |
|-122.26  |37.85   |52.0              |2491.0     |474.0         |1098.0    |468.0     |3.075        |213500.0          |NEAR BAY       |
|-122.26  |37.84   |52.0              |696.0      |191.0         |345.0     |174.0     |2.6736       |191300.0          |NEAR BAY       |
|-122.26  |37.85   |52.0              |2643.0     |626.0         |1212.0    |620.0     |1.9167       |159200.0          |NEAR BAY       |
|-122.26  |37.85   |50.0              |1120.0     |283.0         |697.0     |264.0     |2.125        |140000.0          |NEAR BAY       |
|-122.27  |37.85   |52.0              |1966.0     |347.0         |793.0     |331.0     |2.775        |152500.0          |NEAR BAY       |
|-122.27  |37.85   |52.0              |1228.0     |293.0         |648.0     |303.0     |2.1202       |155500.0          |NEAR BAY       |
|-122.26  |37.84   |50.0              |2239.0     |455.0         |990.0     |419.0     |1.9911       |158700.0          |NEAR BAY       |
|-122.27  |37.84   |52.0              |1503.0     |298.0         |690.0     |275.0     |2.6033       |162900.0          |NEAR BAY       |
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

#### Copy One Column

In [17]:
df.withColumn("CopiedColumn",col("Total_rooms")*100).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|CopiedColumn|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|     88000.0|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|    709900.0|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|    146700.0|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|    127400.0|
|  -122.25|   37.85|              52.0|     1627.0|         280.0|     565.0|     259.0|       3.8462|          342200.0|       NEAR BAY|    162700.0|
|  -122.25|   37.85|              52.0|      919.0|         213.0|     413.0|     193.0|       4.0368|          269700.0|       NEAR BAY|     91900.0|
|  -122.25|   37.84|              52.0|     2535.0|         489.0|    1094.0|     514.0|       3.6591|          299200.0|       NEAR BAY|    253500.0|
|  -122.25|   37.84|              52.0|     3104.0|         687.0|    1157.0|     647.0|         3.12|          241400.0|       NEAR BAY|    310400.0|
|  -122.26|   37.84|              42.0|     2555.0|         665.0|    1206.0|     595.0|       2.0804|          226700.0|       NEAR BAY|    255500.0|
|  -122.25|   37.84|              52.0|     3549.0|         707.0|    1551.0|     714.0|       3.6912|          261100.0|       NEAR BAY|    354900.0|
|  -122.26|   37.85|              52.0|     2202.0|         434.0|     910.0|     402.0|       3.2031|          281500.0|       NEAR BAY|    220200.0|
|  -122.26|   37.85|              52.0|     3503.0|         752.0|    1504.0|     734.0|       3.2705|          241800.0|       NEAR BAY|    350300.0|
|  -122.26|   37.85|              52.0|     2491.0|         474.0|    1098.0|     468.0|        3.075|          213500.0|       NEAR BAY|    249100.0|
|  -122.26|   37.84|              52.0|      696.0|         191.0|     345.0|     174.0|       2.6736|          191300.0|       NEAR BAY|     69600.0|
|  -122.26|   37.85|              52.0|     2643.0|         626.0|    1212.0|     620.0|       1.9167|          159200.0|       NEAR BAY|    264300.0|
|  -122.26|   37.85|              50.0|     1120.0|         283.0|     697.0|     264.0|        2.125|          140000.0|       NEAR BAY|    112000.0|
|  -122.27|   37.85|              52.0|     1966.0|         347.0|     793.0|     331.0|        2.775|          152500.0|       NEAR BAY|    196600.0|
|  -122.27|   37.85|              52.0|     1228.0|         293.0|     648.0|     303.0|       2.1202|          155500.0|       NEAR BAY|    122800.0|
|  -122.26|   37.84|              50.0|     2239.0|         455.0|     990.0|     419.0|       1.9911|          158700.0|       NEAR BAY|    223900.0|
|  -122.27|   37.84|              52.0|     1503.0|         298.0|     690.0|     275.0|       2.6033|          162900.0|       NEAR BAY|    150300.0|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+------------+
only showing top 20 rows

#### Drop a Column

In [18]:
df.drop("copiedColumn")

DataFrame[longitude: double, latitude: double, housing_median_age: double, total_rooms: double, total_bedrooms: double, population: double, households: double, median_income: double, median_house_value: double, ocean_proximity: string]

In [19]:
df.show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1627.0|         280.0|     565.0|     259.0|       3.8462|          342200.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|      919.0|         213.0|     413.0|     193.0|       4.0368|          269700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     2535.0|         489.0|    1094.0|     514.0|       3.6591|          299200.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3104.0|         687.0|    1157.0|     647.0|         3.12|          241400.0|       NEAR BAY|
|  -122.26|   37.84|              42.0|     2555.0|         665.0|    1206.0|     595.0|       2.0804|          226700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3549.0|         707.0|    1551.0|     714.0|       3.6912|          261100.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2202.0|         434.0|     910.0|     402.0|       3.2031|          281500.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     3503.0|         752.0|    1504.0|     734.0|       3.2705|          241800.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2491.0|         474.0|    1098.0|     468.0|        3.075|          213500.0|       NEAR BAY|
|  -122.26|   37.84|              52.0|      696.0|         191.0|     345.0|     174.0|       2.6736|          191300.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2643.0|         626.0|    1212.0|     620.0|       1.9167|          159200.0|       NEAR BAY|
|  -122.26|   37.85|              50.0|     1120.0|         283.0|     697.0|     264.0|        2.125|          140000.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1966.0|         347.0|     793.0|     331.0|        2.775|          152500.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1228.0|         293.0|     648.0|     303.0|       2.1202|          155500.0|       NEAR BAY|
|  -122.26|   37.84|              50.0|     2239.0|         455.0|     990.0|     419.0|       1.9911|          158700.0|       NEAR BAY|
|  -122.27|   37.84|              52.0|     1503.0|         298.0|     690.0|     275.0|       2.6033|          162900.0|       NEAR BAY|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

#### Filter

In [20]:
df.filter(df.latitude== 37.85).show(truncate=False)

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|-122.24  |37.85   |52.0              |1467.0     |190.0         |496.0     |177.0     |7.2574       |352100.0          |NEAR BAY       |
|-122.25  |37.85   |52.0              |1274.0     |235.0         |558.0     |219.0     |5.6431       |341300.0          |NEAR BAY       |
|-122.25  |37.85   |52.0              |1627.0     |280.0         |565.0     |259.0     |3.8462       |342200.0          |NEAR BAY       |
|-122.25  |37.85   |52.0              |919.0      |213.0         |413.0     |193.0     |4.0368       |269700.0          |NEAR BAY       |
|-122.26  |37.85   |52.0              |2202.0     |434.0         |910.0     |402.0     |3.2031       |281500.0          |NEAR BAY       |
|-122.26  |37.85   |52.0              |3503.0     |752.0         |1504.0    |734.0     |3.2705       |241800.0          |NEAR BAY       |
|-122.26  |37.85   |52.0              |2491.0     |474.0         |1098.0    |468.0     |3.075        |213500.0          |NEAR BAY       |
|-122.26  |37.85   |52.0              |2643.0     |626.0         |1212.0    |620.0     |1.9167       |159200.0          |NEAR BAY       |
|-122.26  |37.85   |50.0              |1120.0     |283.0         |697.0     |264.0     |2.125        |140000.0          |NEAR BAY       |
|-122.27  |37.85   |52.0              |1966.0     |347.0         |793.0     |331.0     |2.775        |152500.0          |NEAR BAY       |
|-122.27  |37.85   |52.0              |1228.0     |293.0         |648.0     |303.0     |2.1202       |155500.0          |NEAR BAY       |
|-122.27  |37.85   |40.0              |751.0      |184.0         |409.0     |166.0     |1.3578       |147500.0          |NEAR BAY       |
|-122.27  |37.85   |42.0              |1639.0     |367.0         |929.0     |366.0     |1.7135       |159800.0          |NEAR BAY       |
|-122.28  |37.85   |41.0              |535.0      |123.0         |317.0     |119.0     |2.4038       |107500.0          |NEAR BAY       |
|-122.28  |37.85   |49.0              |1130.0     |244.0         |607.0     |239.0     |2.4597       |93800.0           |NEAR BAY       |
|-122.28  |37.85   |52.0              |1898.0     |421.0         |1102.0    |397.0     |1.808        |105500.0          |NEAR BAY       |
|-122.24  |37.85   |37.0              |334.0      |54.0          |98.0      |47.0      |4.9643       |335000.0          |NEAR BAY       |
|-122.23  |37.85   |52.0              |2800.0     |411.0         |1061.0    |403.0     |6.3434       |373600.0          |NEAR BAY       |
|-122.24  |37.85   |52.0              |2612.0     |365.0         |901.0     |367.0     |7.2354       |391100.0          |NEAR BAY       |
|-122.22  |37.85   |28.0              |5287.0     |1048.0        |2031.0    |956.0     |5.457        |337300.0          |NEAR BAY       |
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [22]:
df.filter(df.ocean_proximity!="NEAR BAY").show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -121.97|   37.64|              32.0|     1283.0|         194.0|     485.0|     171.0|       6.0574|          431000.0|      <1H OCEAN|
|  -121.99|   37.61|               9.0|     3666.0|         711.0|    2341.0|     703.0|       4.6458|          217000.0|      <1H OCEAN|
|  -121.97|   37.57|              21.0|     4342.0|         783.0|    2172.0|     789.0|       4.6146|          247600.0|      <1H OCEAN|
|  -121.96|   37.58|              15.0|     3575.0|         597.0|    1777.0|     559.0|       5.7192|          283500.0|      <1H OCEAN|
|  -121.98|   37.58|              20.0|     4126.0|        1031.0|    2079.0|     975.0|       3.6832|          216900.0|      <1H OCEAN|
|  -121.99|   37.58|              31.0|     2878.0|         478.0|    1276.0|     485.0|       6.2073|          282500.0|      <1H OCEAN|
|   -122.0|   37.58|               6.0|     4405.0|         717.0|    2071.0|     688.0|       5.8151|          295600.0|      <1H OCEAN|
|  -121.93|   37.49|               5.0|     1150.0|         311.0|     648.0|     245.0|       3.5714|          300000.0|      <1H OCEAN|
|  -121.99|   37.56|              18.0|     5505.0|        1005.0|    2641.0|     971.0|          5.0|          269700.0|      <1H OCEAN|
|  -121.99|   37.56|              20.0|     6462.0|        1294.0|    3288.0|    1235.0|       4.3393|          231200.0|      <1H OCEAN|
|  -121.96|   37.55|               4.0|     3746.0|         993.0|    1606.0|     838.0|       4.1387|          162500.0|      <1H OCEAN|
|  -121.97|   37.56|              13.0|     8918.0|        1823.0|    4518.0|    1772.0|       4.8052|          254000.0|      <1H OCEAN|
|  -121.97|   37.54|              31.0|     1949.0|         344.0|     986.0|     322.0|       4.6349|          196200.0|      <1H OCEAN|
|  -121.97|   37.55|              17.0|     4924.0|        1247.0|    3080.0|    1182.0|        3.168|          189400.0|      <1H OCEAN|
|  -121.98|   37.54|              17.0|     5133.0|        1375.0|    3386.0|    1339.0|       3.1326|          220800.0|      <1H OCEAN|
|  -121.99|   37.55|              16.0|     6647.0|        2098.0|    4649.0|    1903.0|       2.9074|          213800.0|      <1H OCEAN|
|  -121.94|   37.56|              15.0|     5674.0|         748.0|    2412.0|     714.0|       8.3996|          442900.0|      <1H OCEAN|
|  -121.95|   37.55|              21.0|    10687.0|        1540.0|    4552.0|    1520.0|       6.6478|          333400.0|      <1H OCEAN|
|  -121.93|   37.54|              25.0|     1354.0|         192.0|     596.0|     220.0|        6.629|          352400.0|      <1H OCEAN|
|  -121.94|   37.54|              27.0|     3715.0|         526.0|    1631.0|     538.0|       6.2179|          305300.0|      <1H OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [23]:
df.filter(~(df.ocean_proximity=="NEAR BAY")).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -121.97|   37.64|              32.0|     1283.0|         194.0|     485.0|     171.0|       6.0574|          431000.0|      <1H OCEAN|
|  -121.99|   37.61|               9.0|     3666.0|         711.0|    2341.0|     703.0|       4.6458|          217000.0|      <1H OCEAN|
|  -121.97|   37.57|              21.0|     4342.0|         783.0|    2172.0|     789.0|       4.6146|          247600.0|      <1H OCEAN|
|  -121.96|   37.58|              15.0|     3575.0|         597.0|    1777.0|     559.0|       5.7192|          283500.0|      <1H OCEAN|
|  -121.98|   37.58|              20.0|     4126.0|        1031.0|    2079.0|     975.0|       3.6832|          216900.0|      <1H OCEAN|
|  -121.99|   37.58|              31.0|     2878.0|         478.0|    1276.0|     485.0|       6.2073|          282500.0|      <1H OCEAN|
|   -122.0|   37.58|               6.0|     4405.0|         717.0|    2071.0|     688.0|       5.8151|          295600.0|      <1H OCEAN|
|  -121.93|   37.49|               5.0|     1150.0|         311.0|     648.0|     245.0|       3.5714|          300000.0|      <1H OCEAN|
|  -121.99|   37.56|              18.0|     5505.0|        1005.0|    2641.0|     971.0|          5.0|          269700.0|      <1H OCEAN|
|  -121.99|   37.56|              20.0|     6462.0|        1294.0|    3288.0|    1235.0|       4.3393|          231200.0|      <1H OCEAN|
|  -121.96|   37.55|               4.0|     3746.0|         993.0|    1606.0|     838.0|       4.1387|          162500.0|      <1H OCEAN|
|  -121.97|   37.56|              13.0|     8918.0|        1823.0|    4518.0|    1772.0|       4.8052|          254000.0|      <1H OCEAN|
|  -121.97|   37.54|              31.0|     1949.0|         344.0|     986.0|     322.0|       4.6349|          196200.0|      <1H OCEAN|
|  -121.97|   37.55|              17.0|     4924.0|        1247.0|    3080.0|    1182.0|        3.168|          189400.0|      <1H OCEAN|
|  -121.98|   37.54|              17.0|     5133.0|        1375.0|    3386.0|    1339.0|       3.1326|          220800.0|      <1H OCEAN|
|  -121.99|   37.55|              16.0|     6647.0|        2098.0|    4649.0|    1903.0|       2.9074|          213800.0|      <1H OCEAN|
|  -121.94|   37.56|              15.0|     5674.0|         748.0|    2412.0|     714.0|       8.3996|          442900.0|      <1H OCEAN|
|  -121.95|   37.55|              21.0|    10687.0|        1540.0|    4552.0|    1520.0|       6.6478|          333400.0|      <1H OCEAN|
|  -121.93|   37.54|              25.0|     1354.0|         192.0|     596.0|     220.0|        6.629|          352400.0|      <1H OCEAN|
|  -121.94|   37.54|              27.0|     3715.0|         526.0|    1631.0|     538.0|       6.2179|          305300.0|      <1H OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [24]:
df.filter(col("ocean_proximity")=="NEAR BAY").show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1627.0|         280.0|     565.0|     259.0|       3.8462|          342200.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|      919.0|         213.0|     413.0|     193.0|       4.0368|          269700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     2535.0|         489.0|    1094.0|     514.0|       3.6591|          299200.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3104.0|         687.0|    1157.0|     647.0|         3.12|          241400.0|       NEAR BAY|
|  -122.26|   37.84|              42.0|     2555.0|         665.0|    1206.0|     595.0|       2.0804|          226700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3549.0|         707.0|    1551.0|     714.0|       3.6912|          261100.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2202.0|         434.0|     910.0|     402.0|       3.2031|          281500.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     3503.0|         752.0|    1504.0|     734.0|       3.2705|          241800.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2491.0|         474.0|    1098.0|     468.0|        3.075|          213500.0|       NEAR BAY|
|  -122.26|   37.84|              52.0|      696.0|         191.0|     345.0|     174.0|       2.6736|          191300.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2643.0|         626.0|    1212.0|     620.0|       1.9167|          159200.0|       NEAR BAY|
|  -122.26|   37.85|              50.0|     1120.0|         283.0|     697.0|     264.0|        2.125|          140000.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1966.0|         347.0|     793.0|     331.0|        2.775|          152500.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1228.0|         293.0|     648.0|     303.0|       2.1202|          155500.0|       NEAR BAY|
|  -122.26|   37.84|              50.0|     2239.0|         455.0|     990.0|     419.0|       1.9911|          158700.0|       NEAR BAY|
|  -122.27|   37.84|              52.0|     1503.0|         298.0|     690.0|     275.0|       2.6033|          162900.0|       NEAR BAY|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [28]:
df.filter("ocean_proximity=='NEAR BAY'").show()  ### SQL EXPRESSION
df.filter("ocean_proximity!='NEAR BAY'").show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1627.0|         280.0|     565.0|     259.0|       3.8462|          342200.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|      919.0|         213.0|     413.0|     193.0|       4.0368|          269700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     2535.0|         489.0|    1094.0|     514.0|       3.6591|          299200.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3104.0|         687.0|    1157.0|     647.0|         3.12|          241400.0|       NEAR BAY|
|  -122.26|   37.84|              42.0|     2555.0|         665.0|    1206.0|     595.0|       2.0804|          226700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3549.0|         707.0|    1551.0|     714.0|       3.6912|          261100.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2202.0|         434.0|     910.0|     402.0|       3.2031|          281500.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     3503.0|         752.0|    1504.0|     734.0|       3.2705|          241800.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2491.0|         474.0|    1098.0|     468.0|        3.075|          213500.0|       NEAR BAY|
|  -122.26|   37.84|              52.0|      696.0|         191.0|     345.0|     174.0|       2.6736|          191300.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2643.0|         626.0|    1212.0|     620.0|       1.9167|          159200.0|       NEAR BAY|
|  -122.26|   37.85|              50.0|     1120.0|         283.0|     697.0|     264.0|        2.125|          140000.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1966.0|         347.0|     793.0|     331.0|        2.775|          152500.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1228.0|         293.0|     648.0|     303.0|       2.1202|          155500.0|       NEAR BAY|
|  -122.26|   37.84|              50.0|     2239.0|         455.0|     990.0|     419.0|       1.9911|          158700.0|       NEAR BAY|
|  -122.27|   37.84|              52.0|     1503.0|         298.0|     690.0|     275.0|       2.6033|          162900.0|       NEAR BAY|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -121.97|   37.64|              32.0|     1283.0|         194.0|     485.0|     171.0|       6.0574|          431000.0|      <1H OCEAN|
|  -121.99|   37.61|               9.0|     3666.0|         711.0|    2341.0|     703.0|       4.6458|          217000.0|      <1H OCEAN|
|  -121.97|   37.57|              21.0|     4342.0|         783.0|    2172.0|     789.0|       4.6146|          247600.0|      <1H OCEAN|
|  -121.96|   37.58|              15.0|     3575.0|         597.0|    1777.0|     559.0|       5.7192|          283500.0|      <1H OCEAN|
|  -121.98|   37.58|              20.0|     4126.0|        1031.0|    2079.0|     975.0|       3.6832|          216900.0|      <1H OCEAN|
|  -121.99|   37.58|              31.0|     2878.0|         478.0|    1276.0|     485.0|       6.2073|          282500.0|      <1H OCEAN|
|   -122.0|   37.58|               6.0|     4405.0|         717.0|    2071.0|     688.0|       5.8151|          295600.0|      <1H OCEAN|
|  -121.93|   37.49|               5.0|     1150.0|         311.0|     648.0|     245.0|       3.5714|          300000.0|      <1H OCEAN|
|  -121.99|   37.56|              18.0|     5505.0|        1005.0|    2641.0|     971.0|          5.0|          269700.0|      <1H OCEAN|
|  -121.99|   37.56|              20.0|     6462.0|        1294.0|    3288.0|    1235.0|       4.3393|          231200.0|      <1H OCEAN|
|  -121.96|   37.55|               4.0|     3746.0|         993.0|    1606.0|     838.0|       4.1387|          162500.0|      <1H OCEAN|
|  -121.97|   37.56|              13.0|     8918.0|        1823.0|    4518.0|    1772.0|       4.8052|          254000.0|      <1H OCEAN|
|  -121.97|   37.54|              31.0|     1949.0|         344.0|     986.0|     322.0|       4.6349|          196200.0|      <1H OCEAN|
|  -121.97|   37.55|              17.0|     4924.0|        1247.0|    3080.0|    1182.0|        3.168|          189400.0|      <1H OCEAN|
|  -121.98|   37.54|              17.0|     5133.0|        1375.0|    3386.0|    1339.0|       3.1326|          220800.0|      <1H OCEAN|
|  -121.99|   37.55|              16.0|     6647.0|        2098.0|    4649.0|    1903.0|       2.9074|          213800.0|      <1H OCEAN|
|  -121.94|   37.56|              15.0|     5674.0|         748.0|    2412.0|     714.0|       8.3996|          442900.0|      <1H OCEAN|
|  -121.95|   37.55|              21.0|    10687.0|        1540.0|    4552.0|    1520.0|       6.6478|          333400.0|      <1H OCEAN|
|  -121.93|   37.54|              25.0|     1354.0|         192.0|     596.0|     220.0|        6.629|          352400.0|      <1H OCEAN|
|  -121.94|   37.54|              27.0|     3715.0|         526.0|    1631.0|     538.0|       6.2179|          305300.0|      <1H OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [33]:
df.filter("ocean_proximity<>'NEAR BAY'").show()  ##Not equal to

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -121.97|   37.64|              32.0|     1283.0|         194.0|     485.0|     171.0|       6.0574|          431000.0|      <1H OCEAN|
|  -121.99|   37.61|               9.0|     3666.0|         711.0|    2341.0|     703.0|       4.6458|          217000.0|      <1H OCEAN|
|  -121.97|   37.57|              21.0|     4342.0|         783.0|    2172.0|     789.0|       4.6146|          247600.0|      <1H OCEAN|
|  -121.96|   37.58|              15.0|     3575.0|         597.0|    1777.0|     559.0|       5.7192|          283500.0|      <1H OCEAN|
|  -121.98|   37.58|              20.0|     4126.0|        1031.0|    2079.0|     975.0|       3.6832|          216900.0|      <1H OCEAN|
|  -121.99|   37.58|              31.0|     2878.0|         478.0|    1276.0|     485.0|       6.2073|          282500.0|      <1H OCEAN|
|   -122.0|   37.58|               6.0|     4405.0|         717.0|    2071.0|     688.0|       5.8151|          295600.0|      <1H OCEAN|
|  -121.93|   37.49|               5.0|     1150.0|         311.0|     648.0|     245.0|       3.5714|          300000.0|      <1H OCEAN|
|  -121.99|   37.56|              18.0|     5505.0|        1005.0|    2641.0|     971.0|          5.0|          269700.0|      <1H OCEAN|
|  -121.99|   37.56|              20.0|     6462.0|        1294.0|    3288.0|    1235.0|       4.3393|          231200.0|      <1H OCEAN|
|  -121.96|   37.55|               4.0|     3746.0|         993.0|    1606.0|     838.0|       4.1387|          162500.0|      <1H OCEAN|
|  -121.97|   37.56|              13.0|     8918.0|        1823.0|    4518.0|    1772.0|       4.8052|          254000.0|      <1H OCEAN|
|  -121.97|   37.54|              31.0|     1949.0|         344.0|     986.0|     322.0|       4.6349|          196200.0|      <1H OCEAN|
|  -121.97|   37.55|              17.0|     4924.0|        1247.0|    3080.0|    1182.0|        3.168|          189400.0|      <1H OCEAN|
|  -121.98|   37.54|              17.0|     5133.0|        1375.0|    3386.0|    1339.0|       3.1326|          220800.0|      <1H OCEAN|
|  -121.99|   37.55|              16.0|     6647.0|        2098.0|    4649.0|    1903.0|       2.9074|          213800.0|      <1H OCEAN|
|  -121.94|   37.56|              15.0|     5674.0|         748.0|    2412.0|     714.0|       8.3996|          442900.0|      <1H OCEAN|
|  -121.95|   37.55|              21.0|    10687.0|        1540.0|    4552.0|    1520.0|       6.6478|          333400.0|      <1H OCEAN|
|  -121.93|   37.54|              25.0|     1354.0|         192.0|     596.0|     220.0|        6.629|          352400.0|      <1H OCEAN|
|  -121.94|   37.54|              27.0|     3715.0|         526.0|    1631.0|     538.0|       6.2179|          305300.0|      <1H OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [35]:
df.filter((df.ocean_proximity=="NEAR BAY")&(df.latitude=="37.85")).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1627.0|         280.0|     565.0|     259.0|       3.8462|          342200.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|      919.0|         213.0|     413.0|     193.0|       4.0368|          269700.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2202.0|         434.0|     910.0|     402.0|       3.2031|          281500.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     3503.0|         752.0|    1504.0|     734.0|       3.2705|          241800.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2491.0|         474.0|    1098.0|     468.0|        3.075|          213500.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2643.0|         626.0|    1212.0|     620.0|       1.9167|          159200.0|       NEAR BAY|
|  -122.26|   37.85|              50.0|     1120.0|         283.0|     697.0|     264.0|        2.125|          140000.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1966.0|         347.0|     793.0|     331.0|        2.775|          152500.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1228.0|         293.0|     648.0|     303.0|       2.1202|          155500.0|       NEAR BAY|
|  -122.27|   37.85|              40.0|      751.0|         184.0|     409.0|     166.0|       1.3578|          147500.0|       NEAR BAY|
|  -122.27|   37.85|              42.0|     1639.0|         367.0|     929.0|     366.0|       1.7135|          159800.0|       NEAR BAY|
|  -122.28|   37.85|              41.0|      535.0|         123.0|     317.0|     119.0|       2.4038|          107500.0|       NEAR BAY|
|  -122.28|   37.85|              49.0|     1130.0|         244.0|     607.0|     239.0|       2.4597|           93800.0|       NEAR BAY|
|  -122.28|   37.85|              52.0|     1898.0|         421.0|    1102.0|     397.0|        1.808|          105500.0|       NEAR BAY|
|  -122.24|   37.85|              37.0|      334.0|          54.0|      98.0|      47.0|       4.9643|          335000.0|       NEAR BAY|
|  -122.23|   37.85|              52.0|     2800.0|         411.0|    1061.0|     403.0|       6.3434|          373600.0|       NEAR BAY|
|  -122.24|   37.85|              52.0|     2612.0|         365.0|     901.0|     367.0|       7.2354|          391100.0|       NEAR BAY|
|  -122.22|   37.85|              28.0|     5287.0|        1048.0|    2031.0|     956.0|        5.457|          337300.0|       NEAR BAY|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [36]:
df.filter((df.ocean_proximity=="NEAR BAY")|(df.latitude=="37.85")).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1627.0|         280.0|     565.0|     259.0|       3.8462|          342200.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|      919.0|         213.0|     413.0|     193.0|       4.0368|          269700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     2535.0|         489.0|    1094.0|     514.0|       3.6591|          299200.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3104.0|         687.0|    1157.0|     647.0|         3.12|          241400.0|       NEAR BAY|
|  -122.26|   37.84|              42.0|     2555.0|         665.0|    1206.0|     595.0|       2.0804|          226700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3549.0|         707.0|    1551.0|     714.0|       3.6912|          261100.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2202.0|         434.0|     910.0|     402.0|       3.2031|          281500.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     3503.0|         752.0|    1504.0|     734.0|       3.2705|          241800.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2491.0|         474.0|    1098.0|     468.0|        3.075|          213500.0|       NEAR BAY|
|  -122.26|   37.84|              52.0|      696.0|         191.0|     345.0|     174.0|       2.6736|          191300.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2643.0|         626.0|    1212.0|     620.0|       1.9167|          159200.0|       NEAR BAY|
|  -122.26|   37.85|              50.0|     1120.0|         283.0|     697.0|     264.0|        2.125|          140000.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1966.0|         347.0|     793.0|     331.0|        2.775|          152500.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1228.0|         293.0|     648.0|     303.0|       2.1202|          155500.0|       NEAR BAY|
|  -122.26|   37.84|              50.0|     2239.0|         455.0|     990.0|     419.0|       1.9911|          158700.0|       NEAR BAY|
|  -122.27|   37.84|              52.0|     1503.0|         298.0|     690.0|     275.0|       2.6033|          162900.0|       NEAR BAY|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

#### Filter isin()

In [37]:
list=[37.84,37.85]
df.filter(df.latitude.isin(list)).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1627.0|         280.0|     565.0|     259.0|       3.8462|          342200.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|      919.0|         213.0|     413.0|     193.0|       4.0368|          269700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     2535.0|         489.0|    1094.0|     514.0|       3.6591|          299200.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3104.0|         687.0|    1157.0|     647.0|         3.12|          241400.0|       NEAR BAY|
|  -122.26|   37.84|              42.0|     2555.0|         665.0|    1206.0|     595.0|       2.0804|          226700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3549.0|         707.0|    1551.0|     714.0|       3.6912|          261100.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2202.0|         434.0|     910.0|     402.0|       3.2031|          281500.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     3503.0|         752.0|    1504.0|     734.0|       3.2705|          241800.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2491.0|         474.0|    1098.0|     468.0|        3.075|          213500.0|       NEAR BAY|
|  -122.26|   37.84|              52.0|      696.0|         191.0|     345.0|     174.0|       2.6736|          191300.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2643.0|         626.0|    1212.0|     620.0|       1.9167|          159200.0|       NEAR BAY|
|  -122.26|   37.85|              50.0|     1120.0|         283.0|     697.0|     264.0|        2.125|          140000.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1966.0|         347.0|     793.0|     331.0|        2.775|          152500.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1228.0|         293.0|     648.0|     303.0|       2.1202|          155500.0|       NEAR BAY|
|  -122.26|   37.84|              50.0|     2239.0|         455.0|     990.0|     419.0|       1.9911|          158700.0|       NEAR BAY|
|  -122.27|   37.84|              52.0|     1503.0|         298.0|     690.0|     275.0|       2.6033|          162900.0|       NEAR BAY|
|  -122.27|   37.85|              40.0|      751.0|         184.0|     409.0|     166.0|       1.3578|          147500.0|       NEAR BAY|
|  -122.27|   37.85|              42.0|     1639.0|         367.0|     929.0|     366.0|       1.7135|          159800.0|       NEAR BAY|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

#### Filter startswith(), endswith(), contains()

In [40]:
df.filter(df.ocean_proximity.startswith("N")).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1627.0|         280.0|     565.0|     259.0|       3.8462|          342200.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|      919.0|         213.0|     413.0|     193.0|       4.0368|          269700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     2535.0|         489.0|    1094.0|     514.0|       3.6591|          299200.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3104.0|         687.0|    1157.0|     647.0|         3.12|          241400.0|       NEAR BAY|
|  -122.26|   37.84|              42.0|     2555.0|         665.0|    1206.0|     595.0|       2.0804|          226700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3549.0|         707.0|    1551.0|     714.0|       3.6912|          261100.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2202.0|         434.0|     910.0|     402.0|       3.2031|          281500.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     3503.0|         752.0|    1504.0|     734.0|       3.2705|          241800.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2491.0|         474.0|    1098.0|     468.0|        3.075|          213500.0|       NEAR BAY|
|  -122.26|   37.84|              52.0|      696.0|         191.0|     345.0|     174.0|       2.6736|          191300.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2643.0|         626.0|    1212.0|     620.0|       1.9167|          159200.0|       NEAR BAY|
|  -122.26|   37.85|              50.0|     1120.0|         283.0|     697.0|     264.0|        2.125|          140000.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1966.0|         347.0|     793.0|     331.0|        2.775|          152500.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1228.0|         293.0|     648.0|     303.0|       2.1202|          155500.0|       NEAR BAY|
|  -122.26|   37.84|              50.0|     2239.0|         455.0|     990.0|     419.0|       1.9911|          158700.0|       NEAR BAY|
|  -122.27|   37.84|              52.0|     1503.0|         298.0|     690.0|     275.0|       2.6033|          162900.0|       NEAR BAY|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [42]:
df.filter(df.ocean_proximity.endswith("Y")).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1627.0|         280.0|     565.0|     259.0|       3.8462|          342200.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|      919.0|         213.0|     413.0|     193.0|       4.0368|          269700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     2535.0|         489.0|    1094.0|     514.0|       3.6591|          299200.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3104.0|         687.0|    1157.0|     647.0|         3.12|          241400.0|       NEAR BAY|
|  -122.26|   37.84|              42.0|     2555.0|         665.0|    1206.0|     595.0|       2.0804|          226700.0|       NEAR BAY|
|  -122.25|   37.84|              52.0|     3549.0|         707.0|    1551.0|     714.0|       3.6912|          261100.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2202.0|         434.0|     910.0|     402.0|       3.2031|          281500.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     3503.0|         752.0|    1504.0|     734.0|       3.2705|          241800.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2491.0|         474.0|    1098.0|     468.0|        3.075|          213500.0|       NEAR BAY|
|  -122.26|   37.84|              52.0|      696.0|         191.0|     345.0|     174.0|       2.6736|          191300.0|       NEAR BAY|
|  -122.26|   37.85|              52.0|     2643.0|         626.0|    1212.0|     620.0|       1.9167|          159200.0|       NEAR BAY|
|  -122.26|   37.85|              50.0|     1120.0|         283.0|     697.0|     264.0|        2.125|          140000.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1966.0|         347.0|     793.0|     331.0|        2.775|          152500.0|       NEAR BAY|
|  -122.27|   37.85|              52.0|     1228.0|         293.0|     648.0|     303.0|       2.1202|          155500.0|       NEAR BAY|
|  -122.26|   37.84|              50.0|     2239.0|         455.0|     990.0|     419.0|       1.9911|          158700.0|       NEAR BAY|
|  -122.27|   37.84|              52.0|     1503.0|         298.0|     690.0|     275.0|       2.6033|          162900.0|       NEAR BAY|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [44]:
df.filter(df.ocean_proximity.contains("H")).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -121.97|   37.64|              32.0|     1283.0|         194.0|     485.0|     171.0|       6.0574|          431000.0|      <1H OCEAN|
|  -121.99|   37.61|               9.0|     3666.0|         711.0|    2341.0|     703.0|       4.6458|          217000.0|      <1H OCEAN|
|  -121.97|   37.57|              21.0|     4342.0|         783.0|    2172.0|     789.0|       4.6146|          247600.0|      <1H OCEAN|
|  -121.96|   37.58|              15.0|     3575.0|         597.0|    1777.0|     559.0|       5.7192|          283500.0|      <1H OCEAN|
|  -121.98|   37.58|              20.0|     4126.0|        1031.0|    2079.0|     975.0|       3.6832|          216900.0|      <1H OCEAN|
|  -121.99|   37.58|              31.0|     2878.0|         478.0|    1276.0|     485.0|       6.2073|          282500.0|      <1H OCEAN|
|   -122.0|   37.58|               6.0|     4405.0|         717.0|    2071.0|     688.0|       5.8151|          295600.0|      <1H OCEAN|
|  -121.93|   37.49|               5.0|     1150.0|         311.0|     648.0|     245.0|       3.5714|          300000.0|      <1H OCEAN|
|  -121.99|   37.56|              18.0|     5505.0|        1005.0|    2641.0|     971.0|          5.0|          269700.0|      <1H OCEAN|
|  -121.99|   37.56|              20.0|     6462.0|        1294.0|    3288.0|    1235.0|       4.3393|          231200.0|      <1H OCEAN|
|  -121.96|   37.55|               4.0|     3746.0|         993.0|    1606.0|     838.0|       4.1387|          162500.0|      <1H OCEAN|
|  -121.97|   37.56|              13.0|     8918.0|        1823.0|    4518.0|    1772.0|       4.8052|          254000.0|      <1H OCEAN|
|  -121.97|   37.54|              31.0|     1949.0|         344.0|     986.0|     322.0|       4.6349|          196200.0|      <1H OCEAN|
|  -121.97|   37.55|              17.0|     4924.0|        1247.0|    3080.0|    1182.0|        3.168|          189400.0|      <1H OCEAN|
|  -121.98|   37.54|              17.0|     5133.0|        1375.0|    3386.0|    1339.0|       3.1326|          220800.0|      <1H OCEAN|
|  -121.99|   37.55|              16.0|     6647.0|        2098.0|    4649.0|    1903.0|       2.9074|          213800.0|      <1H OCEAN|
|  -121.94|   37.56|              15.0|     5674.0|         748.0|    2412.0|     714.0|       8.3996|          442900.0|      <1H OCEAN|
|  -121.95|   37.55|              21.0|    10687.0|        1540.0|    4552.0|    1520.0|       6.6478|          333400.0|      <1H OCEAN|
|  -121.93|   37.54|              25.0|     1354.0|         192.0|     596.0|     220.0|        6.629|          352400.0|      <1H OCEAN|
|  -121.94|   37.54|              27.0|     3715.0|         526.0|    1631.0|     538.0|       6.2179|          305300.0|      <1H OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [50]:
df.filter(df.ocean_proximity.like("%H%")).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -121.97|   37.64|              32.0|     1283.0|         194.0|     485.0|     171.0|       6.0574|          431000.0|      <1H OCEAN|
|  -121.99|   37.61|               9.0|     3666.0|         711.0|    2341.0|     703.0|       4.6458|          217000.0|      <1H OCEAN|
|  -121.97|   37.57|              21.0|     4342.0|         783.0|    2172.0|     789.0|       4.6146|          247600.0|      <1H OCEAN|
|  -121.96|   37.58|              15.0|     3575.0|         597.0|    1777.0|     559.0|       5.7192|          283500.0|      <1H OCEAN|
|  -121.98|   37.58|              20.0|     4126.0|        1031.0|    2079.0|     975.0|       3.6832|          216900.0|      <1H OCEAN|
|  -121.99|   37.58|              31.0|     2878.0|         478.0|    1276.0|     485.0|       6.2073|          282500.0|      <1H OCEAN|
|   -122.0|   37.58|               6.0|     4405.0|         717.0|    2071.0|     688.0|       5.8151|          295600.0|      <1H OCEAN|
|  -121.93|   37.49|               5.0|     1150.0|         311.0|     648.0|     245.0|       3.5714|          300000.0|      <1H OCEAN|
|  -121.99|   37.56|              18.0|     5505.0|        1005.0|    2641.0|     971.0|          5.0|          269700.0|      <1H OCEAN|
|  -121.99|   37.56|              20.0|     6462.0|        1294.0|    3288.0|    1235.0|       4.3393|          231200.0|      <1H OCEAN|
|  -121.96|   37.55|               4.0|     3746.0|         993.0|    1606.0|     838.0|       4.1387|          162500.0|      <1H OCEAN|
|  -121.97|   37.56|              13.0|     8918.0|        1823.0|    4518.0|    1772.0|       4.8052|          254000.0|      <1H OCEAN|
|  -121.97|   37.54|              31.0|     1949.0|         344.0|     986.0|     322.0|       4.6349|          196200.0|      <1H OCEAN|
|  -121.97|   37.55|              17.0|     4924.0|        1247.0|    3080.0|    1182.0|        3.168|          189400.0|      <1H OCEAN|
|  -121.98|   37.54|              17.0|     5133.0|        1375.0|    3386.0|    1339.0|       3.1326|          220800.0|      <1H OCEAN|
|  -121.99|   37.55|              16.0|     6647.0|        2098.0|    4649.0|    1903.0|       2.9074|          213800.0|      <1H OCEAN|
|  -121.94|   37.56|              15.0|     5674.0|         748.0|    2412.0|     714.0|       8.3996|          442900.0|      <1H OCEAN|
|  -121.95|   37.55|              21.0|    10687.0|        1540.0|    4552.0|    1520.0|       6.6478|          333400.0|      <1H OCEAN|
|  -121.93|   37.54|              25.0|     1354.0|         192.0|     596.0|     220.0|        6.629|          352400.0|      <1H OCEAN|
|  -121.94|   37.54|              27.0|     3715.0|         526.0|    1631.0|     538.0|       6.2179|          305300.0|      <1H OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [55]:
###########from pyspark.sql.functions import array_contains
###########df.filter(array_contains(df.ocean_proximity, "NEAR BAY")).show(truncate=False)  #### ocean _proximity is string type. If array type then this works

#### What is the difference between where and filter in PySpark?
In PySpark, both filter() and where() functions are used to select out data based on certain conditions.
They are used interchangeably, and both of them essentially perform the same operation.

#### DROP DUPLICATES

In [61]:
DISTINCTDF=df.distinct()
#print("DISTINCT COUNT :" +str(DISTINCTDF.count()))
print(f"DISTINCT COUNT : {DISTINCTDF.count()}")
DISTINCTDF.show()

DISTINCT COUNT : 20640
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.28|   37.81|              52.0|      340.0|          97.0|     200.0|      87.0|       1.5208|          112500.0|       NEAR BAY|
|  -122.13|   37.67|              40.0|     1748.0|         318.0|     914.0|     317.0|       3.8676|          184000.0|       NEAR BAY|
|  -122.07|   37.67|              27.0|     3239.0|         671.0|    1469.0|     616.0|       3.2465|          230600.0|       NEAR BAY|
|  -122.13|   37.66|              19.0|      862.0|         167.0|     407.0|     183.0|       4.3456|          163000.0|       NEAR BAY|
|  -121.85|   39.73|              52.0|      444.0|          80.0|    1107.0|      98.0|       3.4191|          137500.0|         INLAND|
|  -121.85|    38.0|              26.0|     3364.0|         570.0|    1806.0|     566.0|       4.2647|          133400.0|         INLAND|
|  -121.87|   37.99|              15.0|     2203.0|         312.0|    1051.0|     311.0|       4.9783|          163900.0|         INLAND|
|  -119.98|   38.93|              25.0|     1262.0|         293.0|     534.0|     226.0|       2.6607|           90400.0|         INLAND|
|  -119.78|   36.76|              47.0|     1425.0|         323.0|     949.0|     325.0|       1.7344|           51300.0|         INLAND|
|   -119.6|   36.57|              42.0|     2311.0|         439.0|    1347.0|     436.0|       2.5556|           69700.0|         INLAND|
|  -124.05|   40.85|              31.0|     2414.0|         428.0|    1005.0|     401.0|       3.5156|          143000.0|     NEAR OCEAN|
|  -119.77|    36.3|              24.0|     2202.0|         471.0|    1052.0|     439.0|       2.1038|           62000.0|         INLAND|
|  -122.68|   38.76|              29.0|      994.0|         226.0|     302.0|     117.0|       2.3125|           67900.0|         INLAND|
|  -118.36|   34.16|              45.0|     1755.0|         335.0|     822.0|     342.0|       5.1423|          322900.0|      <1H OCEAN|
|  -118.35|   34.09|              47.0|     1800.0|         546.0|     921.0|     478.0|       2.8021|          280600.0|      <1H OCEAN|
|  -118.19|   34.08|              35.0|     1554.0|         381.0|    1487.0|     374.0|       1.9038|          139500.0|      <1H OCEAN|
|  -118.33|   34.03|              46.0|     2312.0|         625.0|    1552.0|     603.0|       1.6429|          125000.0|      <1H OCEAN|
|  -118.31|   34.02|              46.0|     1976.0|         469.0|    1409.0|     431.0|       2.2981|          112100.0|      <1H OCEAN|
|  -118.25|   34.01|              45.0|      782.0|         270.0|    1030.0|     235.0|       1.0898|           93400.0|      <1H OCEAN|
|  -118.28|   33.97|              31.0|     2017.0|         566.0|    2063.0|     521.0|       1.9219|          107000.0|      <1H OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [62]:
df.count()

20640

In [75]:
df2=df.dropDuplicates()
print("DISTINCT VALUE COUNT :", df2.count())
df2.show()

DISTINCT VALUE COUNT : 20640
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.28|   37.81|              52.0|      340.0|          97.0|     200.0|      87.0|       1.5208|          112500.0|       NEAR BAY|
|  -122.13|   37.67|              40.0|     1748.0|         318.0|     914.0|     317.0|       3.8676|          184000.0|       NEAR BAY|
|  -122.07|   37.67|              27.0|     3239.0|         671.0|    1469.0|     616.0|       3.2465|          230600.0|       NEAR BAY|
|  -122.13|   37.66|              19.0|      862.0|         167.0|     407.0|     183.0|       4.3456|          163000.0|       NEAR BAY|
|  -121.85|   39.73|              52.0|      444.0|          80.0|    1107.0|      98.0|       3.4191|          137500.0|         INLAND|
|  -121.85|    38.0|              26.0|     3364.0|         570.0|    1806.0|     566.0|       4.2647|          133400.0|         INLAND|
|  -121.87|   37.99|              15.0|     2203.0|         312.0|    1051.0|     311.0|       4.9783|          163900.0|         INLAND|
|  -119.98|   38.93|              25.0|     1262.0|         293.0|     534.0|     226.0|       2.6607|           90400.0|         INLAND|
|  -119.78|   36.76|              47.0|     1425.0|         323.0|     949.0|     325.0|       1.7344|           51300.0|         INLAND|
|   -119.6|   36.57|              42.0|     2311.0|         439.0|    1347.0|     436.0|       2.5556|           69700.0|         INLAND|
|  -124.05|   40.85|              31.0|     2414.0|         428.0|    1005.0|     401.0|       3.5156|          143000.0|     NEAR OCEAN|
|  -119.77|    36.3|              24.0|     2202.0|         471.0|    1052.0|     439.0|       2.1038|           62000.0|         INLAND|
|  -122.68|   38.76|              29.0|      994.0|         226.0|     302.0|     117.0|       2.3125|           67900.0|         INLAND|
|  -118.36|   34.16|              45.0|     1755.0|         335.0|     822.0|     342.0|       5.1423|          322900.0|      <1H OCEAN|
|  -118.35|   34.09|              47.0|     1800.0|         546.0|     921.0|     478.0|       2.8021|          280600.0|      <1H OCEAN|
|  -118.19|   34.08|              35.0|     1554.0|         381.0|    1487.0|     374.0|       1.9038|          139500.0|      <1H OCEAN|
|  -118.33|   34.03|              46.0|     2312.0|         625.0|    1552.0|     603.0|       1.6429|          125000.0|      <1H OCEAN|
|  -118.31|   34.02|              46.0|     1976.0|         469.0|    1409.0|     431.0|       2.2981|          112100.0|      <1H OCEAN|
|  -118.25|   34.01|              45.0|      782.0|         270.0|    1030.0|     235.0|       1.0898|           93400.0|      <1H OCEAN|
|  -118.28|   33.97|              31.0|     2017.0|         566.0|    2063.0|     521.0|       1.9219|          107000.0|      <1H OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

#### PySpark Drop duplicates of Selected Multiple Columns

In [79]:
#dropDupDF= df.dropDuplicates(["ocean_proximity","latitude"])

dropDupDF= df.dropDuplicates(["ocean_proximity"])
print(dropDupDF.count())
dropDupDF.show(truncate=False)

5
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|-118.32  |33.35   |27.0              |1675.0     |521.0         |744.0     |331.0     |2.1579       |450000.0          |ISLAND         |
|-124.17  |41.8    |16.0              |2739.0     |480.0         |1259.0    |436.0     |3.7557       |109400.0          |NEAR OCEAN     |
|-122.23  |37.88   |41.0              |880.0      |129.0         |322.0     |126.0     |8.3252       |452600.0          |NEAR BAY       |
|-121.97  |37.64   |32.0              |1283.0     |194.0         |485.0     |171.0     |6.0574       |431000.0          |<1H OCEAN      |
|-121.92  |37.64   |46.0              |1280.0     |209.0         |512.0     |208.0     |5.1406       |315600.0          |INLAND         |
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+

##### How is distinct() different from dropDuplicates()
distinct() and dropDuplicates() in PySpark are used to remove duplicate rows, but there is a subtle difference. distinct() considers all columns when identifying duplicates, while dropDuplicates() allowing you to specify a subset of columns to determine uniqueness

##### How does distinct() handle NULL values?
The distinct() function treats NULL values as equal, so if there are multiple rows with NULL values in all columns, only one of them will be retained after applying distinct()..

###############################################################################################################

### Sort() and orderBy()

In [82]:
df.sort("latitude", "longitude", ascending=[True, False]).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -117.04|   32.54|               7.0|      938.0|         297.0|    1187.0|     282.0|       1.2667|           67500.0|     NEAR OCEAN|
|  -117.04|   32.55|              15.0|     2206.0|         648.0|    2511.0|     648.0|       1.6348|           93200.0|     NEAR OCEAN|
|  -117.06|   32.55|               5.0|     3223.0|         940.0|    3284.0|     854.0|       1.4384|          108800.0|     NEAR OCEAN|
|  -117.09|   32.55|               8.0|     6533.0|        1217.0|    4797.0|    1177.0|       3.9583|          144400.0|     NEAR OCEAN|
|  -116.97|   32.56|              23.0|     1262.0|         294.0|    5176.0|     275.0|       2.5625|          153300.0|     NEAR OCEAN|
|  -117.05|   32.56|              22.0|     2172.0|         563.0|    2049.0|     524.0|       2.0159|          139300.0|     NEAR OCEAN|
|  -117.05|   32.56|              18.0|     1215.0|         320.0|    1195.0|     349.0|       1.9875|          114900.0|     NEAR OCEAN|
|  -117.05|   32.56|              17.0|      985.0|         233.0|     811.0|     223.0|        2.875|          134500.0|     NEAR OCEAN|
|  -117.06|   32.56|              17.0|     2803.0|         683.0|    2768.0|     676.0|       1.7958|          140400.0|     NEAR OCEAN|
|  -117.06|   32.56|               5.0|     2706.0|         925.0|    3148.0|     855.0|       1.7301|          125000.0|     NEAR OCEAN|
|  -117.07|   32.56|               9.0|     3648.0|         895.0|    3293.0|     840.0|       3.0992|          142600.0|     NEAR OCEAN|
|  -117.09|   32.56|               8.0|      864.0|         156.0|     626.0|     172.0|       4.8984|          151500.0|     NEAR OCEAN|
|   -117.1|   32.56|              16.0|     2687.0|         501.0|    1502.0|     480.0|         3.75|          146800.0|     NEAR OCEAN|
|  -117.12|   32.56|              20.0|     2524.0|         682.0|    1819.0|     560.0|       2.9286|          257700.0|     NEAR OCEAN|
|  -117.05|   32.57|              22.0|     2857.0|         516.0|    2412.0|     496.0|       4.7337|          127600.0|     NEAR OCEAN|
|  -117.05|   32.57|              13.0|     2880.0|         576.0|    2450.0|     567.0|       3.1696|          138000.0|     NEAR OCEAN|
|  -117.06|   32.57|              16.0|     1269.0|         282.0|    1609.0|     298.0|       2.6985|          156500.0|     NEAR OCEAN|
|  -117.06|   32.57|              17.0|     2252.0|         378.0|    1776.0|     365.0|       4.6364|          141100.0|     NEAR OCEAN|
|  -117.06|   32.57|              25.0|     1268.0|         282.0|     991.0|     299.0|       3.0284|          123600.0|     NEAR OCEAN|
|  -117.06|   32.57|              18.0|     1384.0|         311.0|    1429.0|     287.0|       1.3362|           95000.0|     NEAR OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [83]:
df.sort("latitude",ascending=True).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -117.04|   32.54|               7.0|      938.0|         297.0|    1187.0|     282.0|       1.2667|           67500.0|     NEAR OCEAN|
|  -117.04|   32.55|              15.0|     2206.0|         648.0|    2511.0|     648.0|       1.6348|           93200.0|     NEAR OCEAN|
|  -117.06|   32.55|               5.0|     3223.0|         940.0|    3284.0|     854.0|       1.4384|          108800.0|     NEAR OCEAN|
|  -117.09|   32.55|               8.0|     6533.0|        1217.0|    4797.0|    1177.0|       3.9583|          144400.0|     NEAR OCEAN|
|  -117.05|   32.56|              18.0|     1215.0|         320.0|    1195.0|     349.0|       1.9875|          114900.0|     NEAR OCEAN|
|  -117.05|   32.56|              17.0|      985.0|         233.0|     811.0|     223.0|        2.875|          134500.0|     NEAR OCEAN|
|  -116.97|   32.56|              23.0|     1262.0|         294.0|    5176.0|     275.0|       2.5625|          153300.0|     NEAR OCEAN|
|  -117.05|   32.56|              22.0|     2172.0|         563.0|    2049.0|     524.0|       2.0159|          139300.0|     NEAR OCEAN|
|  -117.06|   32.56|              17.0|     2803.0|         683.0|    2768.0|     676.0|       1.7958|          140400.0|     NEAR OCEAN|
|  -117.06|   32.56|               5.0|     2706.0|         925.0|    3148.0|     855.0|       1.7301|          125000.0|     NEAR OCEAN|
|   -117.1|   32.56|              16.0|     2687.0|         501.0|    1502.0|     480.0|         3.75|          146800.0|     NEAR OCEAN|
|  -117.07|   32.56|               9.0|     3648.0|         895.0|    3293.0|     840.0|       3.0992|          142600.0|     NEAR OCEAN|
|  -117.09|   32.56|               8.0|      864.0|         156.0|     626.0|     172.0|       4.8984|          151500.0|     NEAR OCEAN|
|  -117.12|   32.56|              20.0|     2524.0|         682.0|    1819.0|     560.0|       2.9286|          257700.0|     NEAR OCEAN|
|  -117.06|   32.57|              16.0|     1269.0|         282.0|    1609.0|     298.0|       2.6985|          156500.0|     NEAR OCEAN|
|   -117.1|   32.57|              26.0|     2343.0|         371.0|    1221.0|     372.0|       4.3601|          144900.0|     NEAR OCEAN|
|  -117.05|   32.57|              22.0|     2857.0|         516.0|    2412.0|     496.0|       4.7337|          127600.0|     NEAR OCEAN|
|  -117.06|   32.57|              25.0|     1268.0|         282.0|     991.0|     299.0|       3.0284|          123600.0|     NEAR OCEAN|
|  -117.06|   32.57|              17.0|     2252.0|         378.0|    1776.0|     365.0|       4.6364|          141100.0|     NEAR OCEAN|
|  -117.05|   32.57|              13.0|     2880.0|         576.0|    2450.0|     567.0|       3.1696|          138000.0|     NEAR OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [84]:
df.sort(col("latitude"),ascending=True).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -117.04|   32.54|               7.0|      938.0|         297.0|    1187.0|     282.0|       1.2667|           67500.0|     NEAR OCEAN|
|  -117.04|   32.55|              15.0|     2206.0|         648.0|    2511.0|     648.0|       1.6348|           93200.0|     NEAR OCEAN|
|  -117.06|   32.55|               5.0|     3223.0|         940.0|    3284.0|     854.0|       1.4384|          108800.0|     NEAR OCEAN|
|  -117.09|   32.55|               8.0|     6533.0|        1217.0|    4797.0|    1177.0|       3.9583|          144400.0|     NEAR OCEAN|
|  -117.05|   32.56|              18.0|     1215.0|         320.0|    1195.0|     349.0|       1.9875|          114900.0|     NEAR OCEAN|
|  -117.05|   32.56|              17.0|      985.0|         233.0|     811.0|     223.0|        2.875|          134500.0|     NEAR OCEAN|
|  -116.97|   32.56|              23.0|     1262.0|         294.0|    5176.0|     275.0|       2.5625|          153300.0|     NEAR OCEAN|
|  -117.05|   32.56|              22.0|     2172.0|         563.0|    2049.0|     524.0|       2.0159|          139300.0|     NEAR OCEAN|
|  -117.06|   32.56|              17.0|     2803.0|         683.0|    2768.0|     676.0|       1.7958|          140400.0|     NEAR OCEAN|
|  -117.06|   32.56|               5.0|     2706.0|         925.0|    3148.0|     855.0|       1.7301|          125000.0|     NEAR OCEAN|
|   -117.1|   32.56|              16.0|     2687.0|         501.0|    1502.0|     480.0|         3.75|          146800.0|     NEAR OCEAN|
|  -117.07|   32.56|               9.0|     3648.0|         895.0|    3293.0|     840.0|       3.0992|          142600.0|     NEAR OCEAN|
|  -117.09|   32.56|               8.0|      864.0|         156.0|     626.0|     172.0|       4.8984|          151500.0|     NEAR OCEAN|
|  -117.12|   32.56|              20.0|     2524.0|         682.0|    1819.0|     560.0|       2.9286|          257700.0|     NEAR OCEAN|
|  -117.06|   32.57|              16.0|     1269.0|         282.0|    1609.0|     298.0|       2.6985|          156500.0|     NEAR OCEAN|
|   -117.1|   32.57|              26.0|     2343.0|         371.0|    1221.0|     372.0|       4.3601|          144900.0|     NEAR OCEAN|
|  -117.05|   32.57|              22.0|     2857.0|         516.0|    2412.0|     496.0|       4.7337|          127600.0|     NEAR OCEAN|
|  -117.06|   32.57|              25.0|     1268.0|         282.0|     991.0|     299.0|       3.0284|          123600.0|     NEAR OCEAN|
|  -117.06|   32.57|              17.0|     2252.0|         378.0|    1776.0|     365.0|       4.6364|          141100.0|     NEAR OCEAN|
|  -117.05|   32.57|              13.0|     2880.0|         576.0|    2450.0|     567.0|       3.1696|          138000.0|     NEAR OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [86]:
df.orderBy("latitude", "ocean_proximity").show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -117.04|   32.54|               7.0|      938.0|         297.0|    1187.0|     282.0|       1.2667|           67500.0|     NEAR OCEAN|
|  -117.04|   32.55|              15.0|     2206.0|         648.0|    2511.0|     648.0|       1.6348|           93200.0|     NEAR OCEAN|
|  -117.06|   32.55|               5.0|     3223.0|         940.0|    3284.0|     854.0|       1.4384|          108800.0|     NEAR OCEAN|
|  -117.09|   32.55|               8.0|     6533.0|        1217.0|    4797.0|    1177.0|       3.9583|          144400.0|     NEAR OCEAN|
|  -117.05|   32.56|              18.0|     1215.0|         320.0|    1195.0|     349.0|       1.9875|          114900.0|     NEAR OCEAN|
|  -117.05|   32.56|              17.0|      985.0|         233.0|     811.0|     223.0|        2.875|          134500.0|     NEAR OCEAN|
|  -116.97|   32.56|              23.0|     1262.0|         294.0|    5176.0|     275.0|       2.5625|          153300.0|     NEAR OCEAN|
|  -117.05|   32.56|              22.0|     2172.0|         563.0|    2049.0|     524.0|       2.0159|          139300.0|     NEAR OCEAN|
|  -117.06|   32.56|              17.0|     2803.0|         683.0|    2768.0|     676.0|       1.7958|          140400.0|     NEAR OCEAN|
|  -117.06|   32.56|               5.0|     2706.0|         925.0|    3148.0|     855.0|       1.7301|          125000.0|     NEAR OCEAN|
|   -117.1|   32.56|              16.0|     2687.0|         501.0|    1502.0|     480.0|         3.75|          146800.0|     NEAR OCEAN|
|  -117.07|   32.56|               9.0|     3648.0|         895.0|    3293.0|     840.0|       3.0992|          142600.0|     NEAR OCEAN|
|  -117.09|   32.56|               8.0|      864.0|         156.0|     626.0|     172.0|       4.8984|          151500.0|     NEAR OCEAN|
|  -117.12|   32.56|              20.0|     2524.0|         682.0|    1819.0|     560.0|       2.9286|          257700.0|     NEAR OCEAN|
|  -117.06|   32.57|              16.0|     1269.0|         282.0|    1609.0|     298.0|       2.6985|          156500.0|     NEAR OCEAN|
|   -117.1|   32.57|              26.0|     2343.0|         371.0|    1221.0|     372.0|       4.3601|          144900.0|     NEAR OCEAN|
|  -117.05|   32.57|              22.0|     2857.0|         516.0|    2412.0|     496.0|       4.7337|          127600.0|     NEAR OCEAN|
|  -117.06|   32.57|              25.0|     1268.0|         282.0|     991.0|     299.0|       3.0284|          123600.0|     NEAR OCEAN|
|  -117.06|   32.57|              17.0|     2252.0|         378.0|    1776.0|     365.0|       4.6364|          141100.0|     NEAR OCEAN|
|  -117.05|   32.57|              13.0|     2880.0|         576.0|    2450.0|     567.0|       3.1696|          138000.0|     NEAR OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [88]:
df.orderBy(col("latitude"),col("longitude"),ascending=True).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -117.04|   32.54|               7.0|      938.0|         297.0|    1187.0|     282.0|       1.2667|           67500.0|     NEAR OCEAN|
|  -117.09|   32.55|               8.0|     6533.0|        1217.0|    4797.0|    1177.0|       3.9583|          144400.0|     NEAR OCEAN|
|  -117.06|   32.55|               5.0|     3223.0|         940.0|    3284.0|     854.0|       1.4384|          108800.0|     NEAR OCEAN|
|  -117.04|   32.55|              15.0|     2206.0|         648.0|    2511.0|     648.0|       1.6348|           93200.0|     NEAR OCEAN|
|  -117.12|   32.56|              20.0|     2524.0|         682.0|    1819.0|     560.0|       2.9286|          257700.0|     NEAR OCEAN|
|   -117.1|   32.56|              16.0|     2687.0|         501.0|    1502.0|     480.0|         3.75|          146800.0|     NEAR OCEAN|
|  -117.09|   32.56|               8.0|      864.0|         156.0|     626.0|     172.0|       4.8984|          151500.0|     NEAR OCEAN|
|  -117.07|   32.56|               9.0|     3648.0|         895.0|    3293.0|     840.0|       3.0992|          142600.0|     NEAR OCEAN|
|  -117.06|   32.56|               5.0|     2706.0|         925.0|    3148.0|     855.0|       1.7301|          125000.0|     NEAR OCEAN|
|  -117.06|   32.56|              17.0|     2803.0|         683.0|    2768.0|     676.0|       1.7958|          140400.0|     NEAR OCEAN|
|  -117.05|   32.56|              18.0|     1215.0|         320.0|    1195.0|     349.0|       1.9875|          114900.0|     NEAR OCEAN|
|  -117.05|   32.56|              17.0|      985.0|         233.0|     811.0|     223.0|        2.875|          134500.0|     NEAR OCEAN|
|  -117.05|   32.56|              22.0|     2172.0|         563.0|    2049.0|     524.0|       2.0159|          139300.0|     NEAR OCEAN|
|  -116.97|   32.56|              23.0|     1262.0|         294.0|    5176.0|     275.0|       2.5625|          153300.0|     NEAR OCEAN|
|  -117.12|   32.57|              21.0|     1738.0|         295.0|     983.0|     298.0|       4.8274|          174100.0|     NEAR OCEAN|
|  -117.12|   32.57|              35.0|     1450.0|         256.0|     930.0|     286.0|       2.6715|          133300.0|     NEAR OCEAN|
|  -117.11|   32.57|              32.0|     2723.0|         586.0|    1702.0|     562.0|       3.3371|          140500.0|     NEAR OCEAN|
|   -117.1|   32.57|              26.0|     2343.0|         371.0|    1221.0|     372.0|       4.3601|          144900.0|     NEAR OCEAN|
|   -117.1|   32.57|              14.0|     5058.0|        1299.0|    3662.0|    1193.0|       2.3253|          133700.0|     NEAR OCEAN|
|  -117.09|   32.57|              23.0|     1817.0|         323.0|    1371.0|     327.0|       3.6736|          139500.0|     NEAR OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [89]:
df.orderBy(col("latitude").asc(),col("longitude").desc()).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -117.04|   32.54|               7.0|      938.0|         297.0|    1187.0|     282.0|       1.2667|           67500.0|     NEAR OCEAN|
|  -117.04|   32.55|              15.0|     2206.0|         648.0|    2511.0|     648.0|       1.6348|           93200.0|     NEAR OCEAN|
|  -117.06|   32.55|               5.0|     3223.0|         940.0|    3284.0|     854.0|       1.4384|          108800.0|     NEAR OCEAN|
|  -117.09|   32.55|               8.0|     6533.0|        1217.0|    4797.0|    1177.0|       3.9583|          144400.0|     NEAR OCEAN|
|  -116.97|   32.56|              23.0|     1262.0|         294.0|    5176.0|     275.0|       2.5625|          153300.0|     NEAR OCEAN|
|  -117.05|   32.56|              22.0|     2172.0|         563.0|    2049.0|     524.0|       2.0159|          139300.0|     NEAR OCEAN|
|  -117.05|   32.56|              18.0|     1215.0|         320.0|    1195.0|     349.0|       1.9875|          114900.0|     NEAR OCEAN|
|  -117.05|   32.56|              17.0|      985.0|         233.0|     811.0|     223.0|        2.875|          134500.0|     NEAR OCEAN|
|  -117.06|   32.56|              17.0|     2803.0|         683.0|    2768.0|     676.0|       1.7958|          140400.0|     NEAR OCEAN|
|  -117.06|   32.56|               5.0|     2706.0|         925.0|    3148.0|     855.0|       1.7301|          125000.0|     NEAR OCEAN|
|  -117.07|   32.56|               9.0|     3648.0|         895.0|    3293.0|     840.0|       3.0992|          142600.0|     NEAR OCEAN|
|  -117.09|   32.56|               8.0|      864.0|         156.0|     626.0|     172.0|       4.8984|          151500.0|     NEAR OCEAN|
|   -117.1|   32.56|              16.0|     2687.0|         501.0|    1502.0|     480.0|         3.75|          146800.0|     NEAR OCEAN|
|  -117.12|   32.56|              20.0|     2524.0|         682.0|    1819.0|     560.0|       2.9286|          257700.0|     NEAR OCEAN|
|  -117.05|   32.57|              22.0|     2857.0|         516.0|    2412.0|     496.0|       4.7337|          127600.0|     NEAR OCEAN|
|  -117.05|   32.57|              13.0|     2880.0|         576.0|    2450.0|     567.0|       3.1696|          138000.0|     NEAR OCEAN|
|  -117.06|   32.57|              16.0|     1269.0|         282.0|    1609.0|     298.0|       2.6985|          156500.0|     NEAR OCEAN|
|  -117.06|   32.57|              17.0|     2252.0|         378.0|    1776.0|     365.0|       4.6364|          141100.0|     NEAR OCEAN|
|  -117.06|   32.57|              25.0|     1268.0|         282.0|     991.0|     299.0|       3.0284|          123600.0|     NEAR OCEAN|
|  -117.06|   32.57|              18.0|     1384.0|         311.0|    1429.0|     287.0|       1.3362|           95000.0|     NEAR OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

In [90]:
df.sort(col("latitude").asc()).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -117.04|   32.54|               7.0|      938.0|         297.0|    1187.0|     282.0|       1.2667|           67500.0|     NEAR OCEAN|
|  -117.04|   32.55|              15.0|     2206.0|         648.0|    2511.0|     648.0|       1.6348|           93200.0|     NEAR OCEAN|
|  -117.06|   32.55|               5.0|     3223.0|         940.0|    3284.0|     854.0|       1.4384|          108800.0|     NEAR OCEAN|
|  -117.09|   32.55|               8.0|     6533.0|        1217.0|    4797.0|    1177.0|       3.9583|          144400.0|     NEAR OCEAN|
|  -117.05|   32.56|              18.0|     1215.0|         320.0|    1195.0|     349.0|       1.9875|          114900.0|     NEAR OCEAN|
|  -117.05|   32.56|              17.0|      985.0|         233.0|     811.0|     223.0|        2.875|          134500.0|     NEAR OCEAN|
|  -116.97|   32.56|              23.0|     1262.0|         294.0|    5176.0|     275.0|       2.5625|          153300.0|     NEAR OCEAN|
|  -117.05|   32.56|              22.0|     2172.0|         563.0|    2049.0|     524.0|       2.0159|          139300.0|     NEAR OCEAN|
|  -117.06|   32.56|              17.0|     2803.0|         683.0|    2768.0|     676.0|       1.7958|          140400.0|     NEAR OCEAN|
|  -117.06|   32.56|               5.0|     2706.0|         925.0|    3148.0|     855.0|       1.7301|          125000.0|     NEAR OCEAN|
|   -117.1|   32.56|              16.0|     2687.0|         501.0|    1502.0|     480.0|         3.75|          146800.0|     NEAR OCEAN|
|  -117.07|   32.56|               9.0|     3648.0|         895.0|    3293.0|     840.0|       3.0992|          142600.0|     NEAR OCEAN|
|  -117.09|   32.56|               8.0|      864.0|         156.0|     626.0|     172.0|       4.8984|          151500.0|     NEAR OCEAN|
|  -117.12|   32.56|              20.0|     2524.0|         682.0|    1819.0|     560.0|       2.9286|          257700.0|     NEAR OCEAN|
|  -117.06|   32.57|              16.0|     1269.0|         282.0|    1609.0|     298.0|       2.6985|          156500.0|     NEAR OCEAN|
|   -117.1|   32.57|              26.0|     2343.0|         371.0|    1221.0|     372.0|       4.3601|          144900.0|     NEAR OCEAN|
|  -117.05|   32.57|              22.0|     2857.0|         516.0|    2412.0|     496.0|       4.7337|          127600.0|     NEAR OCEAN|
|  -117.06|   32.57|              25.0|     1268.0|         282.0|     991.0|     299.0|       3.0284|          123600.0|     NEAR OCEAN|
|  -117.06|   32.57|              17.0|     2252.0|         378.0|    1776.0|     365.0|       4.6364|          141100.0|     NEAR OCEAN|
|  -117.05|   32.57|              13.0|     2880.0|         576.0|    2450.0|     567.0|       3.1696|          138000.0|     NEAR OCEAN|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 20 rows

#### What is the difference between orderBy() and sort() in PySpark?
In PySpark, both orderBy() and sort() are methods used for sorting rows in a DataFrame, and they serve the same purpose. However, there is no significant difference in terms of functionality or sorting capability between these two methods. Both can be used to sort rows based on one or more columns in ascending or descending order.

#################################################################################################################

## groupBy

#### Functions
count(): Use groupBy() count() to return the number of rows for each group.<br>
mean():	Returns the mean of values for each group.<br> 
max(): Returns the maximum of values for each group.<br>
min(): Returns the minimum of values for each group.<br> 
sum(): Returns the total for values for each group.<br> 
agg(): Using groupBy() agg() function, we can calculate more than one aggregate at a time.<br>
pivot(): This function is used to Pivot the DataFrame

In [95]:
df.groupBy("latitude").sum("population").show()

+--------+---------------+
|latitude|sum(population)|
+--------+---------------+
|   37.81|        82042.0|
|   38.61|        58273.0|
|   40.11|         1942.0|
|   35.17|         2514.0|
|   40.53|         2401.0|
|   39.42|         3820.0|
|   40.94|         1457.0|
|   37.23|        44829.0|
|   38.93|         8767.0|
|    37.1|         5930.0|
|   36.27|         3138.0|
|   38.68|        69765.0|
|   35.15|         5156.0|
|   41.46|          600.0|
|   37.42|        32191.0|
|   39.97|         1236.0|
|   41.78|         4294.0|
|   40.05|         1204.0|
|   35.38|        24104.0|
|   35.34|        16641.0|
+--------+---------------+
only showing top 20 rows

In [97]:
df.groupBy("ocean_proximity").count().show()

+---------------+-----+
|ocean_proximity|count|
+---------------+-----+
|         ISLAND|    5|
|     NEAR OCEAN| 2658|
|       NEAR BAY| 2290|
|      <1H OCEAN| 9136|
|         INLAND| 6551|
+---------------+-----+

In [101]:
df.groupBy("ocean_proximity").mean("latitude").show()  #if just mean(): it will show mean  of all the columns.

+---------------+------------------+
|ocean_proximity|     avg(latitude)|
+---------------+------------------+
|         ISLAND|33.358000000000004|
|     NEAR OCEAN| 34.73843867569602|
|       NEAR BAY|37.801056768558915|
|      <1H OCEAN|34.560576838879264|
|         INLAND| 36.73182872843834|
+---------------+------------------+

In [107]:
#df.groupBy("ocean_proximity").max("latitude").show()
df.groupBy("ocean_proximity").max("median_income").show()

+---------------+------------------+
|ocean_proximity|max(median_income)|
+---------------+------------------+
|         ISLAND|            3.3906|
|     NEAR OCEAN|           15.0001|
|       NEAR BAY|           15.0001|
|      <1H OCEAN|           15.0001|
|         INLAND|           15.0001|
+---------------+------------------+

In [108]:
df.groupBy("housing_median_age").min("total_bedrooms").show()

+------------------+-------------------+
|housing_median_age|min(total_bedrooms)|
+------------------+-------------------+
|               8.0|                9.0|
|               7.0|               12.0|
|              49.0|                7.0|
|              29.0|               22.0|
|              47.0|               23.0|
|              42.0|               14.0|
|              44.0|               29.0|
|              35.0|               31.0|
|              18.0|               17.0|
|              39.0|                8.0|
|               1.0|                2.0|
|              37.0|               17.0|
|              34.0|               11.0|
|              25.0|               32.0|
|              36.0|                5.0|
|              41.0|               20.0|
|               4.0|                2.0|
|              23.0|               32.0|
|              50.0|               33.0|
|              45.0|                5.0|
+------------------+-------------------+
only showing top 20 rows

In [111]:
df.groupBy("housing_median_age","median_income").max("total_rooms","total_bedrooms").show()

+------------------+-------------+----------------+-------------------+
|housing_median_age|median_income|max(total_rooms)|max(total_bedrooms)|
+------------------+-------------+----------------+-------------------+
|              18.0|      11.6017|          1617.0|              210.0|
|              52.0|       7.9556|          2079.0|              273.0|
|              31.0|       5.2312|          1487.0|              280.0|
|              19.0|       5.0509|          4657.0|              739.0|
|              22.0|       2.5008|          8350.0|             2717.0|
|              37.0|       4.0924|          2066.0|              434.0|
|              30.0|        4.975|           414.0|               54.0|
|              35.0|         4.75|          2277.0|              420.0|
|              25.0|       5.0423|          5405.0|              939.0|
|              14.0|       5.2798|          5332.0|              884.0|
|              15.0|       5.8418|          1216.0|              166.0|
|              32.0|       2.0353|          1991.0|              504.0|
|              13.0|       4.0709|          4492.0|              821.0|
|              17.0|         3.25|          1415.0|              267.0|
|              24.0|       3.8571|          3756.0|              681.0|
|              23.0|         3.35|          1658.0|              307.0|
|              36.0|       3.3984|          2112.0|              374.0|
|              52.0|       1.4125|           425.0|              119.0|
|              34.0|       3.4286|          2861.0|              510.0|
|              32.0|       2.4306|           993.0|              285.0|
+------------------+-------------+----------------+-------------------+
only showing top 20 rows

In [114]:
from pyspark.sql.functions import max, min
df.groupBy("median_house_value").agg(max("total_rooms").alias("MaxTotalRoomsAvail"), min("total_bedrooms").alias("MinTotalBedroom")).show()

+------------------+------------------+---------------+
|median_house_value|MaxTotalRoomsAvail|MinTotalBedroom|
+------------------+------------------+---------------+
|          270100.0|            3789.0|          162.0|
|          330000.0|            6678.0|           15.0|
|          179300.0|            5031.0|          193.0|
|          217000.0|           15207.0|          338.0|
|          300000.0|            7297.0|          168.0|
|          337200.0|            3047.0|          270.0|
|          147000.0|            2633.0|          284.0|
|          147100.0|            3048.0|          121.0|
|           51300.0|            8502.0|           57.0|
|          181400.0|            6108.0|          312.0|
|          230800.0|            3285.0|          166.0|
|          262800.0|            3085.0|          355.0|
|          169700.0|            3297.0|          534.0|
|          477600.0|            2234.0|          256.0|
|          187200.0|            9963.0|          228.0|
|          197500.0|            9071.0|           59.0|
|          209500.0|            4885.0|          236.0|
|          275100.0|            4626.0|          415.0|
|           87700.0|            2982.0|          303.0|
|          220500.0|            4071.0|          312.0|
+------------------+------------------+---------------+
only showing top 20 rows

In [120]:
df.groupBy("median_house_value").agg(max("total_rooms").alias("MaxTotalRoomsAvail"), min("total_bedrooms").alias("MinTotalBedroom")).where(col("MinTotalBedroom")>3000).show()

+------------------+------------------+---------------+
|median_house_value|MaxTotalRoomsAvail|MinTotalBedroom|
+------------------+------------------+---------------+
|          451100.0|           28258.0|         3864.0|
|          399200.0|           30405.0|         4093.0|
|          322500.0|           18123.0|         3173.0|
|           28300.0|           17738.0|         3114.0|
+------------------+------------------+---------------+

## Join

In [130]:
df.show(5)

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|
|  -122.25|   37.85|              52.0|     1627.0|         280.0|     565.0|     259.0|       3.8462|          342200.0|       NEAR BAY|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+
only showing top 5 rows

In [141]:
from pyspark.sql.functions import monotonically_increasing_id
df_with_index = df.withColumn("index", monotonically_increasing_id())
df_with_index.show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+-----+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|index|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+-----+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|    0|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|    1|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|    2|
|  -122.25|   37.85|              52.0|     1274.0|         235.0|     558.0|     219.0|       5.6431|          341300.0|       NEAR BAY|    3|
|  -122.25|   37.85|              52.0|     1627.0|         280.0|     565.0|     259.0|       3.8462|          342200.0|       NEAR BAY|    4|
|  -122.25|   37.85|              52.0|      919.0|         213.0|     413.0|     193.0|       4.0368|          269700.0|       NEAR BAY|    5|
|  -122.25|   37.84|              52.0|     2535.0|         489.0|    1094.0|     514.0|       3.6591|          299200.0|       NEAR BAY|    6|
|  -122.25|   37.84|              52.0|     3104.0|         687.0|    1157.0|     647.0|         3.12|          241400.0|       NEAR BAY|    7|
|  -122.26|   37.84|              42.0|     2555.0|         665.0|    1206.0|     595.0|       2.0804|          226700.0|       NEAR BAY|    8|
|  -122.25|   37.84|              52.0|     3549.0|         707.0|    1551.0|     714.0|       3.6912|          261100.0|       NEAR BAY|    9|
|  -122.26|   37.85|              52.0|     2202.0|         434.0|     910.0|     402.0|       3.2031|          281500.0|       NEAR BAY|   10|
|  -122.26|   37.85|              52.0|     3503.0|         752.0|    1504.0|     734.0|       3.2705|          241800.0|       NEAR BAY|   11|
|  -122.26|   37.85|              52.0|     2491.0|         474.0|    1098.0|     468.0|        3.075|          213500.0|       NEAR BAY|   12|
|  -122.26|   37.84|              52.0|      696.0|         191.0|     345.0|     174.0|       2.6736|          191300.0|       NEAR BAY|   13|
|  -122.26|   37.85|              52.0|     2643.0|         626.0|    1212.0|     620.0|       1.9167|          159200.0|       NEAR BAY|   14|
|  -122.26|   37.85|              50.0|     1120.0|         283.0|     697.0|     264.0|        2.125|          140000.0|       NEAR BAY|   15|
|  -122.27|   37.85|              52.0|     1966.0|         347.0|     793.0|     331.0|        2.775|          152500.0|       NEAR BAY|   16|
|  -122.27|   37.85|              52.0|     1228.0|         293.0|     648.0|     303.0|       2.1202|          155500.0|       NEAR BAY|   17|
|  -122.26|   37.84|              50.0|     2239.0|         455.0|     990.0|     419.0|       1.9911|          158700.0|       NEAR BAY|   18|
|  -122.27|   37.84|              52.0|     1503.0|         298.0|     690.0|     275.0|       2.6033|          162900.0|       NEAR BAY|   19|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+-----+
only showing top 20 rows

In [170]:
df2= df.limit(20)
df2=df2.withColumn("example_column",col("population")*10)
df2=df2.select("longitude","latitude","example_column","total_rooms")
df2.show()

+---------+--------+--------------+-----------+
|longitude|latitude|example_column|total_rooms|
+---------+--------+--------------+-----------+
|  -122.23|   37.88|        3220.0|      880.0|
|  -122.22|   37.86|       24010.0|     7099.0|
|  -122.24|   37.85|        4960.0|     1467.0|
|  -122.25|   37.85|        5580.0|     1274.0|
|  -122.25|   37.85|        5650.0|     1627.0|
|  -122.25|   37.85|        4130.0|      919.0|
|  -122.25|   37.84|       10940.0|     2535.0|
|  -122.25|   37.84|       11570.0|     3104.0|
|  -122.26|   37.84|       12060.0|     2555.0|
|  -122.25|   37.84|       15510.0|     3549.0|
|  -122.26|   37.85|        9100.0|     2202.0|
|  -122.26|   37.85|       15040.0|     3503.0|
|  -122.26|   37.85|       10980.0|     2491.0|
|  -122.26|   37.84|        3450.0|      696.0|
|  -122.26|   37.85|       12120.0|     2643.0|
|  -122.26|   37.85|        6970.0|     1120.0|
|  -122.27|   37.85|        7930.0|     1966.0|
|  -122.27|   37.85|        6480.0|     1228.0|
|  -122.26|   37.84|        9900.0|     2239.0|
|  -122.27|   37.84|        6900.0|     1503.0|
+---------+--------+--------------+-----------+

In [171]:
df3=df.limit(40)
df3=df3.withColumn("example_column",col("population")*10)
df3=df3.select(df3.median_income, df3.example_column,df3.latitude)
df3.show()

+-------------+--------------+--------+
|median_income|example_column|latitude|
+-------------+--------------+--------+
|       8.3252|        3220.0|   37.88|
|       8.3014|       24010.0|   37.86|
|       7.2574|        4960.0|   37.85|
|       5.6431|        5580.0|   37.85|
|       3.8462|        5650.0|   37.85|
|       4.0368|        4130.0|   37.85|
|       3.6591|       10940.0|   37.84|
|         3.12|       11570.0|   37.84|
|       2.0804|       12060.0|   37.84|
|       3.6912|       15510.0|   37.84|
|       3.2031|        9100.0|   37.85|
|       3.2705|       15040.0|   37.85|
|        3.075|       10980.0|   37.85|
|       2.6736|        3450.0|   37.84|
|       1.9167|       12120.0|   37.85|
|        2.125|        6970.0|   37.85|
|        2.775|        7930.0|   37.85|
|       2.1202|        6480.0|   37.85|
|       1.9911|        9900.0|   37.84|
|       2.6033|        6900.0|   37.84|
+-------------+--------------+--------+
only showing top 20 rows

## JOINS AVAILABLE
Inner Join: Returns only the rows with matching keys in both DataFrames.<br>
Left Join: Returns all rows from the left DataFrame and matching rows from the right DataFrame. <br>
Right Join: Returns all rows from the right DataFrame and matching rows from the left DataFrame. <br>
Full Outer Join: Returns all rows from both DataFrames, including matching and non-matching rows. <br>
Left Semi Join: Returns all rows from the left DataFrame where there is a match in the right DataFrame. <br>
Left Anti Join: Returns all rows from the left DataFrame where there is no match in the right DataFrame. <br>rame.

In [172]:
df2.join(df3,df2.example_column == df3.example_column,"inner").show()

+---------+--------+--------------+-----------+-------------+--------------+--------+
|longitude|latitude|example_column|total_rooms|median_income|example_column|latitude|
+---------+--------+--------------+-----------+-------------+--------------+--------+
|  -122.23|   37.88|        3220.0|      880.0|       8.3252|        3220.0|   37.88|
|  -122.22|   37.86|       24010.0|     7099.0|       8.3014|       24010.0|   37.86|
|  -122.24|   37.85|        4960.0|     1467.0|       7.2574|        4960.0|   37.85|
|  -122.25|   37.85|        5580.0|     1274.0|       5.6431|        5580.0|   37.85|
|  -122.25|   37.85|        5650.0|     1627.0|       3.8462|        5650.0|   37.85|
|  -122.25|   37.85|        4130.0|      919.0|       4.0368|        4130.0|   37.85|
|  -122.25|   37.84|       10940.0|     2535.0|       3.6591|       10940.0|   37.84|
|  -122.25|   37.84|       11570.0|     3104.0|         3.12|       11570.0|   37.84|
|  -122.26|   37.84|       12060.0|     2555.0|       2.0804|       12060.0|   37.84|
|  -122.25|   37.84|       15510.0|     3549.0|       3.6912|       15510.0|   37.84|
|  -122.26|   37.85|        9100.0|     2202.0|       3.2031|        9100.0|   37.85|
|  -122.26|   37.85|       15040.0|     3503.0|       3.2705|       15040.0|   37.85|
|  -122.26|   37.85|       10980.0|     2491.0|        3.075|       10980.0|   37.85|
|  -122.26|   37.84|        3450.0|      696.0|       2.6736|        3450.0|   37.84|
|  -122.26|   37.85|       12120.0|     2643.0|       1.9167|       12120.0|   37.85|
|  -122.26|   37.85|        6970.0|     1120.0|        2.125|        6970.0|   37.85|
|  -122.27|   37.85|        7930.0|     1966.0|        2.775|        7930.0|   37.85|
|  -122.27|   37.85|        6480.0|     1228.0|       2.1202|        6480.0|   37.85|
|  -122.26|   37.84|        9900.0|     2239.0|       1.9911|        9900.0|   37.84|
|  -122.27|   37.84|        6900.0|     1503.0|       2.6033|        6900.0|   37.84|
+---------+--------+--------------+-----------+-------------+--------------+--------+

In [181]:
df2.join(df3,df2.example_column == df3.example_column,"leftouter").show() # can write left or leftouter

+---------+--------+--------------+-----------+-------------+--------------+--------+
|longitude|latitude|example_column|total_rooms|median_income|example_column|latitude|
+---------+--------+--------------+-----------+-------------+--------------+--------+
|  -122.23|   37.88|        3220.0|      880.0|       8.3252|        3220.0|   37.88|
|  -122.22|   37.86|       24010.0|     7099.0|       8.3014|       24010.0|   37.86|
|  -122.24|   37.85|        4960.0|     1467.0|       7.2574|        4960.0|   37.85|
|  -122.25|   37.85|        5580.0|     1274.0|       5.6431|        5580.0|   37.85|
|  -122.25|   37.85|        5650.0|     1627.0|       3.8462|        5650.0|   37.85|
|  -122.25|   37.85|        4130.0|      919.0|       4.0368|        4130.0|   37.85|
|  -122.25|   37.84|       10940.0|     2535.0|       3.6591|       10940.0|   37.84|
|  -122.25|   37.84|       11570.0|     3104.0|         3.12|       11570.0|   37.84|
|  -122.26|   37.84|       12060.0|     2555.0|       2.0804|       12060.0|   37.84|
|  -122.25|   37.84|       15510.0|     3549.0|       3.6912|       15510.0|   37.84|
|  -122.26|   37.85|        9100.0|     2202.0|       3.2031|        9100.0|   37.85|
|  -122.26|   37.85|       15040.0|     3503.0|       3.2705|       15040.0|   37.85|
|  -122.26|   37.85|       10980.0|     2491.0|        3.075|       10980.0|   37.85|
|  -122.26|   37.84|        3450.0|      696.0|       2.6736|        3450.0|   37.84|
|  -122.26|   37.85|       12120.0|     2643.0|       1.9167|       12120.0|   37.85|
|  -122.26|   37.85|        6970.0|     1120.0|        2.125|        6970.0|   37.85|
|  -122.27|   37.85|        7930.0|     1966.0|        2.775|        7930.0|   37.85|
|  -122.27|   37.85|        6480.0|     1228.0|       2.1202|        6480.0|   37.85|
|  -122.26|   37.84|        9900.0|     2239.0|       1.9911|        9900.0|   37.84|
|  -122.27|   37.84|        6900.0|     1503.0|       2.6033|        6900.0|   37.84|
+---------+--------+--------------+-----------+-------------+--------------+--------+

In [182]:
rightouterDF=df2.join(df3,df2.example_column == df3.example_column,"right")
print(rightouterDF.count())
rightouterDF.show()

40
+---------+--------+--------------+-----------+-------------+--------------+--------+
|longitude|latitude|example_column|total_rooms|median_income|example_column|latitude|
+---------+--------+--------------+-----------+-------------+--------------+--------+
|  -122.23|   37.88|        3220.0|      880.0|       8.3252|        3220.0|   37.88|
|  -122.22|   37.86|       24010.0|     7099.0|       8.3014|       24010.0|   37.86|
|  -122.24|   37.85|        4960.0|     1467.0|       7.2574|        4960.0|   37.85|
|  -122.25|   37.85|        5580.0|     1274.0|       5.6431|        5580.0|   37.85|
|  -122.25|   37.85|        5650.0|     1627.0|       3.8462|        5650.0|   37.85|
|  -122.25|   37.85|        4130.0|      919.0|       4.0368|        4130.0|   37.85|
|  -122.25|   37.84|       10940.0|     2535.0|       3.6591|       10940.0|   37.84|
|  -122.25|   37.84|       11570.0|     3104.0|         3.12|       11570.0|   37.84|
|  -122.26|   37.84|       12060.0|     2555.0|       2.0804|       12060.0|   37.84|
|  -122.25|   37.84|       15510.0|     3549.0|       3.6912|       15510.0|   37.84|
|  -122.26|   37.85|        9100.0|     2202.0|       3.2031|        9100.0|   37.85|
|  -122.26|   37.85|       15040.0|     3503.0|       3.2705|       15040.0|   37.85|
|  -122.26|   37.85|       10980.0|     2491.0|        3.075|       10980.0|   37.85|
|  -122.26|   37.84|        3450.0|      696.0|       2.6736|        3450.0|   37.84|
|  -122.26|   37.85|       12120.0|     2643.0|       1.9167|       12120.0|   37.85|
|  -122.26|   37.85|        6970.0|     1120.0|        2.125|        6970.0|   37.85|
|  -122.27|   37.85|        7930.0|     1966.0|        2.775|        7930.0|   37.85|
|  -122.27|   37.85|        6480.0|     1228.0|       2.1202|        6480.0|   37.85|
|  -122.26|   37.84|        9900.0|     2239.0|       1.9911|        9900.0|   37.84|
|  -122.27|   37.84|        6900.0|     1503.0|       2.6033|        6900.0|   37.84|
+---------+--------+--------------+-----------+-------------+--------------+--------+
only showing top 20 rows

In [188]:
full_df=df3.join(df2,df3.example_column == df2. example_column, "full") #full,outer,fullouter
full_df.count()
full_df.show()

+-------------+--------------+--------+---------+--------+--------------+-----------+
|median_income|example_column|latitude|longitude|latitude|example_column|total_rooms|
+-------------+--------------+--------+---------+--------+--------------+-----------+
|       2.4038|        3170.0|   37.85|     NULL|    NULL|          NULL|       NULL|
|       8.3252|        3220.0|   37.88|  -122.23|   37.88|        3220.0|      880.0|
|       2.6736|        3450.0|   37.84|  -122.26|   37.84|        3450.0|      696.0|
|       1.6875|        3950.0|   37.84|     NULL|    NULL|          NULL|       NULL|
|       1.3578|        4090.0|   37.85|     NULL|    NULL|          NULL|       NULL|
|       4.0368|        4130.0|   37.85|  -122.25|   37.85|        4130.0|      919.0|
|       7.2574|        4960.0|   37.85|  -122.24|   37.85|        4960.0|     1467.0|
|       5.6431|        5580.0|   37.85|  -122.25|   37.85|        5580.0|     1274.0|
|       3.8462|        5650.0|   37.85|  -122.25|   37.85|        5650.0|     1627.0|
|       1.4861|        5700.0|   37.83|     NULL|    NULL|          NULL|       NULL|
|       2.4597|        6070.0|   37.85|     NULL|    NULL|          NULL|       NULL|
|       2.1202|        6480.0|   37.85|  -122.27|   37.85|        6480.0|     1228.0|
|         3.48|        6890.0|   37.83|     NULL|    NULL|          NULL|       NULL|
|       2.6033|        6900.0|   37.84|  -122.27|   37.84|        6900.0|     1503.0|
|        2.125|        6970.0|   37.85|  -122.26|   37.85|        6970.0|     1120.0|
|        1.375|        7540.0|   37.83|     NULL|    NULL|          NULL|       NULL|
|        2.775|        7930.0|   37.85|  -122.27|   37.85|        7930.0|     1966.0|
|       2.1806|        8530.0|   37.84|     NULL|    NULL|          NULL|       NULL|
|       1.9274|        8630.0|   37.84|     NULL|    NULL|          NULL|       NULL|
|       1.4103|        9010.0|   37.83|     NULL|    NULL|          NULL|       NULL|
+-------------+--------------+--------+---------+--------+--------------+-----------+
only showing top 20 rows

In [194]:
semi_df=df3.join(df2,df3.example_column == df2. example_column, "leftsemi")
semi_df.count()
semi_df.show()

+-------------+--------------+--------+
|median_income|example_column|latitude|
+-------------+--------------+--------+
|       8.3252|        3220.0|   37.88|
|       8.3014|       24010.0|   37.86|
|       7.2574|        4960.0|   37.85|
|       5.6431|        5580.0|   37.85|
|       3.8462|        5650.0|   37.85|
|       4.0368|        4130.0|   37.85|
|       3.6591|       10940.0|   37.84|
|         3.12|       11570.0|   37.84|
|       2.0804|       12060.0|   37.84|
|       3.6912|       15510.0|   37.84|
|       3.2031|        9100.0|   37.85|
|       3.2705|       15040.0|   37.85|
|        3.075|       10980.0|   37.85|
|       2.6736|        3450.0|   37.84|
|       1.9167|       12120.0|   37.85|
|        2.125|        6970.0|   37.85|
|        2.775|        7930.0|   37.85|
|       2.1202|        6480.0|   37.85|
|       1.9911|        9900.0|   37.84|
|       2.6033|        6900.0|   37.84|
+-------------+--------------+--------+

In [197]:
anti_df=df2.join(df2,df3.example_column == df2.example_column, "leftanti")
anti_df.count()
anti_df.show()

+-------------+--------------+--------+
|median_income|example_column|latitude|
+-------------+--------------+--------+
|       1.3578|        4090.0|   37.85|
|       1.7135|        9290.0|   37.85|
|        1.725|       10150.0|   37.84|
|       2.1806|        8530.0|   37.84|
|          2.6|       10060.0|   37.84|
|       2.4038|        3170.0|   37.85|
|       2.4597|        6070.0|   37.85|
|        1.808|       11020.0|   37.85|
|       1.6424|       11310.0|   37.84|
|       1.6875|        3950.0|   37.84|
|       1.9274|        8630.0|   37.84|
|       1.9615|       11680.0|   37.84|
|       1.7969|       10260.0|   37.84|
|        1.375|        7540.0|   37.83|
|       2.7303|       12580.0|   37.83|
|       1.4861|        5700.0|   37.83|
|       1.0972|        9870.0|   37.83|
|       1.4103|        9010.0|   37.83|
|         3.48|        6890.0|   37.83|
|       2.5898|       13770.0|   37.83|
+-------------+--------------+--------+

#### An example of multiple joins 

df1.join(df2,df1.id1 == df2.id2,"inner") \
   .join(df3,df1.id1 == df3.id3,"inner")